### ISSUE TITLE
missed files

### ISSUE THREAD

**Issue by geemus** [fog/fog-aws#1]
@lanej a couple things just came in under the wire before the switch. Could you pull these in? See: https://github.com/fog/fog/tree/master/lib/fog/aws (the requests/parsers). Might be related test changes to grab too. Sorry I missed that before. Thanks!

**Comment by lanej** [comment]
i pulled them in after the switch.

i.e.
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/parsers/storage/get_bucket_notification.rb

**Comment by geemus** [comment]
Cleaned up leftovers here: https://github.com/fog/fog/commit/3b0a132ac7af499f8b0f073d81975ecd3b9575a3
