### ISSUE TITLE
Why are the credential keys not generalized? 

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#10]
Original issue at: fog/fog#3165

We're currently implementing `fog` in one of our applications and were surprised to find that all of the credential keys for each service are specific to that service.

I would have thought that I'd be able to set something like:

```
STORAGE_PROVIDER=AWS
STORAGE_USERNAME=foo
STORAGE_PASSWORD=bar
```

And in my code do something like:

``` ruby
    @connection ||= Fog::Storage.new(
      provider: ENV['STORAGE_PROVIDER'],
      username: ENV['STORAGE_USERNAME'],
      password: ENV['STORAGE_PASSWORD'])
```

Considering the point of fog is that you can abstract away your cloud providers, then theoretically changing it shouldn't require a code change.

Please let me know if I'm misunderstanding.

Thanks for all the hard work on this!

**Comment by plribeiro3000** [comment]
cc/ @jfelchner @hhd418

**Comment by jfelchner** [comment]
@plribeiro3000 BOOM! :bomb:  LOVE IT! :heart:

**Comment by geemus** [comment]
It's an interesting point, though it would have led to namespace collisions from how we did .fog files among other things unfortunately. Also some services don't use username/password as their keys. So I like the idea, but I think (unfortunately) that it might be hard to implement in a generic way.
