### ISSUE TITLE
IAM authentication not compatible with GovCloud 

### ISSUE THREAD

**Issue by benbalter** [fog/fog-aws#100]
In https://github.com/fog/fog-aws/blob/master/lib/fog/aws/iam.rb#L233, the IAM implementation assumes the region us `us-east-1` for all requets. 

```ruby
#global services that have no region are signed with the us-east-1 region
@signer = Fog::AWS::SignatureV4.new( @aws_access_key_id, @aws_secret_access_key,'us-east-1','iam')
```

This is not true for AWS [GovCloud](https://aws.amazon.com/govcloud-us/), the government-specific AWS region.

If the host is set as `iam.us-gov.amazonaws.com`, a request for `Fog::AWS::IAM#roles` will return:

`Credential should be scoped to a valid region, not 'us-east-1'.`

Instead, I'd suggest that the IAM constructor accept a region argument (to mirror other constructors), which defaults to `us-east-1`, to allow for better GovCloud support.

**Comment by geemus** [comment]
@benbalter sounds reasonable, I suspect we just hadn't stumbled upon this just yet. Would you be up for working on a pull request to fix this? Thanks!

**Comment by benbalter** [comment]
> Would you be up for working on a pull request to fix this?

Sure thing. Done over in https://github.com/fog/fog-aws/pull/102.

**Comment by geemus** [comment]
Awesome, thanks!
