### ISSUE TITLE
"NoMethodError: undefined method `body' for #<Fog::DNS::AWS::Error:0x007f6c673e1720>"

### ISSUE THREAD

**Issue by tysontate** [fog/fog-aws#112]
The following line of code is not expecting a `Fog::DNS::AWS::Error` to be returned, so it's blindly calling `.body` on the result of `service.change_resource_record_sets`:

https://github.com/fog/fog-aws/blob/5903a7819b12ec6feb3b1d4177f9a1f4a4ca3a59/lib/fog/aws/models/dns/record.rb#L44

```
data = service.change_resource_record_sets(zone.id, [options]).body
```

My code is doing the following:

```
record = Fog::DNS['AWS'].zones.get( "......" ).records.new({
  name: "foo.foobar.com",
  value: "ec2-123-123-123-123.compute-1.amazonaws.com",
  ttl: 600,
  type: 'CNAME'
})
record.save # this line raises the error
```

**Comment by geemus** [comment]
Hmm. I wouldn't expect that to return an error though (it should raise it, in which case it should stop execution, rather than calling body). Could you share the rest of the stack trace? I think that might help narrow it down a bit easier. Thanks!

**Comment by tysontate** [comment]
The rest of the stack trace is purely my own application code, actually.

![screen shot 2015-05-14 at 11 37 28 am](https://cloud.githubusercontent.com/assets/111501/7638983/b0d9153e-fa2d-11e4-8e35-296cd29036d9.png)

(Clipped, of course, but that's the top two lines of the stack.)

**Comment by geemus** [comment]
That looks like a pretty old version of fog-aws actually, could you bump it and see if that helps?

**Comment by tysontate** [comment]
Ah! I didn't even notice that. I'll close and re-open if it occurs again with the latest release.

**Comment by geemus** [comment]
No worries, sounds good, thanks!

**Comment by eherot** [comment]
I think this is actually still an issue. Here's what happened when I used a version of fog-aws built from `master`:
```
[6] pry(main)> zone.records.create(record_attributes)                                                           NoMethodError: undefined method `body' for #<Fog::DNS::AWS::Error:0x007fe72abf6d50>
from /Users/eherot/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-aws-0.3.0/lib/fog/aws/models/dns/record.rb:44:in `save'
[7] pry(main)> wtf?
Exception: NoMethodError: undefined method `body' for #<Fog::DNS::AWS::Error:0x007fe72abf6d50>
--
0: /Users/eherot/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-aws-0.3.0/lib/fog/aws/models/dns/record.rb:44:in `save'
1: /Users/eherot/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
2: (pry):6:in `__pry__'
```

**Comment by eherot** [comment]
@tysontate @geemus I think you guys might want to re-open this...

**Comment by tysontate** [comment]
Re-opened!

**Comment by pollosp** [comment]
Same problem with fog-aws (0.4.0):
```
had an error: NoMethodError: undefined method `body' for #<Fog::DNS::AWS::Error:0x007fca91a909d0>
```

**Comment by geemus** [comment]
Looks like we were missing a raise, think the commit above should fix it, sorry for the confusion.

**Comment by josacar** [comment]
Thanks @geemus , it work flawlessly
