### ISSUE TITLE
Fog::Compute::AWS::Error InvalidParameterValue => secondary-addresses

### ISSUE THREAD

**Issue by lantrix** [fog/fog-aws#115]
Using fog to assign a private IP address to an AWS eni, I'm getting this error:

```
Fog::Compute::AWS::Error
------------------------
InvalidParameterValue => secondary-addresses
```

This is to assign a secondary private IP as a VIP for the instance.
This previously worked for me (Ubuntu 12.04 OS) on and eni - but fails now (Ubuntu 14.04) on an eni/instance created using the same recipe.

Recipe lines to create the address are shown below; and I can't see why it's even complaining that `secondary-addresses` is invalid as a param as it's not stipulated.

``` ruby
# Fetch our MAC address
mac = File.read('/sys/class/net/eth0/address').strip
# Use the MAC to get our AWS interface ID
eth0_interface_id = Mixlib::ShellOut.new("curl http://169.254.169.254/latest/meta-data/network/interfaces/macs/#{mac}/interface-id").run_command.stdout

# Create a new AWS compute connection
connection = Fog::Compute.new(
  :provider               => :aws,
  :aws_access_key_id      => node['my_cookbook']['chef_ha_access_key_id'],
  :aws_secret_access_key  => node['my_cookbook']['chef_ha_secret_access_key'],
  :region                 => node['my_cookbook']['region'],
  :endpoint               => "https://ec2.#{node['my_cookbook']['region']}.amazonaws.com/"
)

# Here's where we attach the IP address
connection.assign_private_ip_addresses(eth0_interface_id, 'PrivateIpAddresses' => node['my_cookbook']['backend_vip']['ip_address'], 'AllowReassignment' => true )
```

**Comment by geemus** [comment]
Not obvious to me. @lanej I think you implemented the assign private stuff, could you take a look? Thanks!

**Comment by lanej** [comment]
@lantrix would be useful to see the request body via a stdout instrumentor if possible.

i don't see any references to `secondary-addresses` so I'm curious how it's getting in there.
