### ISSUE TITLE
Creating VPC instances in AWS

### ISSUE THREAD

**Issue by ankitrokdeonsns** [fog/fog-aws#116]
While using Fog::Compute[:aws].servers.bootstrap I cannot create an EC2 instance inside a VPC. To create instance one has to specify `security_group_id` and `subnet_id`. `bootstrap` method does not allow this.

**Comment by geemus** [comment]
Yeah, this is unfortunately true. The bootstrap stuff predates VPC availability and hasn't been updated to support the new options. We would certainly welcome a pull request to remedy this, but in the mean time I believe you should be able to decompose the bootstrap command and run the individual parts to get it to work.

**Comment by ankitrokdeonsns** [comment]
For now I ended up using aws-cli.

**Comment by geemus** [comment]
Fair enough, just let me know if you revisit and would like to work on a pr. Thanks!

**Comment by ankitrokdeonsns** [comment]
Sure

**Comment by hand-of-distillytics** [comment]
I recommend closing this issue.

According to the [Run Instances Documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html)...
> * [EC2-VPC] If you don't specify a subnet ID, we choose a default subnet from your default VPC for you. If you don't have a default VPC, you must specify a subnet ID in the request.

I am able to use `bootstrap` with `subnet_id` and a list of `groups` names to launch EC2-VPC instances... Provided they have permission to use the default security group for that VPC.

**Comment by geemus** [comment]
@hand-of-distillytics Ok, thanks for the update.
