### ISSUE TITLE
Cannot saving auto scaling group

### ISSUE THREAD

**Issue by frankh** [fog/fog-aws#125]
I'm having trouble updating an auto scaling group. It seems to be trying to assign a serialized version of the tags list as a tag, and hitting the tag length limit.

The error I'm getting is:

Value '{&quot;ResourceId&quot;=&gt;&quot;xxxxxxxxxxx-AutoScalingGroup-9O3T0B4Z0E26&quot;, &quot;PropagateAtLaunch&quot;=&gt;true, &quot;Value&quot;=&gt;&quot;xxxxxxxxxxx-Z5ZZTKPWA7WO&quot;, &quot;Key&quot;=&gt;&quot;aws:cloudformation:stack-name&quot;, &quot;ResourceType&quot;=&gt;&quot;auto-scaling-group&quot;}' at 'tags.6.member.key' failed to satisfy constraint: Member must have length less than or equal to 128

**Comment by geemus** [comment]
Sorry to hear that. Could you provide a little more context about what call you are making and with what arguments? I think that will help a lot in terms of narrowing this down, thanks!
