### ISSUE TITLE
Getting SignatureDoesNotMatch error with eu-central-1

### ISSUE THREAD

**Issue by nimser** [fog/fog-aws#127]
When using fog via paperclip with the following configuration: 

```
config.paperclip_defaults = {
  :storage => :fog,
  :fog_credentials => {
    :provider => 'AWS',
    :aws_access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
    :region => 'eu-central-1'
  },
  :fog_directory => ENV['FOG_DIRECTORY']
}
```

Access to S3 fails with the following error: 

```
Excon::Errors::Forbidden: Expected(200) <=> Actual(403 Forbidden)
SignatureDoesNotMatch - The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Logging directly with the `awscli` tools using the same credentials and setting the same region works. I double checked the keys. Also, `aws s3api get-bucket-location --bucket mybucket` returns `eu-central-1`.

**Comment by geemus** [comment]
Are there any other messages? Could you run it with `EXCON_DEBUG=true` and share the output? Thanks!

**Comment by geemus** [comment]
Also, what versions of fog/excon?

**Comment by fcheung** [comment]
If you are using instance provided keys then you need to set the session token too

**Comment by felixbuenemann** [comment]
@fuzzytern Do your headers by chance contain multiple consecutive spaces? If yes, you could be running into issue #160.

**Comment by mshibuya** [comment]
I've run into similar issue and culprit was https://github.com/excon/excon/issues/475.
