### ISSUE TITLE
Fog doesn't support storage_type or gp2 for RDS?

### ISSUE THREAD

**Issue by lockstone** [fog/fog-aws#129]
Hello,

It looks like Fog doesn't support the storage_type (StorageType) parameter for RDS creation, which means there's no way to create an RDS instance that uses General Purpose SSD (gp2). It does have the 'iops' parameter for a Provisioned IOps RDS instance (which assumes a storage_type of 'io1'). But I don't see a way to specify gp2.

Am I misunderstanding something? Is this a missing feature or is it intentional?

Here are the relevant docs in Amazon:

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateInstance.html

http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/CLIReference-cmd-CreateDBInstance.html

**Comment by lanej** [comment]
what about StorageType support is missing ?

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/rds/server.rb#L139
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/rds/server.rb#L37
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/rds/create_db_instance.rb#L30
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/parsers/rds/db_parser.rb#L49

if you are attempting to use it and it's not working, please paste example request/responses.

**Comment by lockstone** [comment]
Ok, got it. I was looking at an old copy of the source that I thought was connected to github but wasn't. And we were also using version 1.29 of fog which was ignoring the storage_type parameter. I upgraded to 1.30 and it's working now. Thanks.
