### ISSUE TITLE
Add support for elasticache redis replication groups

### ISSUE THREAD

**Issue by gergnz** [fog/fog-aws#136]
It would be great if fog had support for replication groups

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Replication.html

http://docs.aws.amazon.com/sdkforruby/api/Aws/ElastiCache/Client.html#create_replication_group-instance_method

**Comment by geemus** [comment]
Agreed, we would certainly welcome a PR if you have the inclination. Otherwise somebody will probably get to it in time. Thanks!
