### ISSUE TITLE
Is anyone going to add support for AWS ElasticTranscoder

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#14]
Original issue at: fog/fog#2875

Or maybe it's done already somewhere. Thanks for the great work on this Gem!

**Comment by plribeiro3000** [comment]
cc/ @johvet

**Comment by kris** [comment]
I'm actually needing this right now, erg.

**Comment by geemus** [comment]
@kris Happy to support work on it, but unfortunately I don't have a need for it (or time to pursue it).
