### ISSUE TITLE
Support for KMS ID for EBS Volume

### ISSUE THREAD

**Issue by kylegoch** [fog/fog-aws#141]
Currently when creating an ebs volume you can set "encrypted" to true and fog will create the encrypted volume. However it uses the master EBS key on the account to do this.

It would be great if there was a "kms_key_id" option like in the AWS CLI to allow you to specify the Key to use for encryption. The value would be a string (Key ARN).

The use in AWS CLI is documented here:
http://docs.aws.amazon.com/cli/latest/reference/ec2/create-volume.html

I dont have the time or knowledge to do a PR for this at the moment so was going to post it none the less. If I get time I will come back and attempt it myself, may be a while though.

**Comment by geemus** [comment]
Thanks for the details and heads up. If there is anything we can help with to make it quicker or easier to help with a PR, just let us know, otherwise it may be a while on our end as well. Thanks!
