### ISSUE TITLE
how to change filepath for html_table_reporter in reporter options

### ISSUE THREAD

**Issue by DeChrish** [fog/fog-aws#167]
I need to include 'html_table_reporter' and need to save the html reports in target filepath, but captureFile option is not workling.

**Comment by lanej** [comment]
@DeChrish i'm sorry but neither of the references correspond to anything in the codebase.  Can you be more specific about what you're trying to do ?

**Comment by DeChrish** [comment]
Mocha options :  
config.mochaTest[name] = {
       options: {
          reporter: 'good-mocha-html-reporter',
          timeout: 60000,
          logErrors: true,
          captureFile: directories.target + '/' + name + '/test-results.html'
        }


good-mocha-html-reporter  - config file:
module.exports = {
           path: '', // full or relative path (relative to your execution folder)
           filename: 'report.html',
           mode: 'Verbose'
}



When i use 'good-mocha-html-reporter' in mocha options, the report is generated as 'report.html' which is added in reporter-config file.
I want to use captureFile option to save the report file.
Is it possible?

**Comment by geemus** [comment]
I suspect you may be reporting this against the wrong project. That doesn't appear to coincide with anything in fog-aws. Perhaps you should ask more directly on the mocha related project?

**Comment by DeChrish** [comment]
oops sorry

**Comment by geemus** [comment]
No problem.
