### ISSUE TITLE
Bring AWS CloudFront API Models/Requests up to date

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#17]
Original issue at: fog/fog#3115

Heaps of missing functionality, specifically around the use of Price Classes, Custom/Dedicated SSL certificates, etc.

Current API version is 3~ years behind, has some authentication breakage when you try and just change the version to 2014-05-31:

```
 response => #<Excon::Response:0x007f991daab9b0 @data={:body=>"<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"http://cloudfront.amazonaws.com/doc/2014-01-31/\"><Error><Type>Sender</Type><Code>IncompleteSignature</Code><Message>Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter.
```

**Comment by plribeiro3000** [comment]
cc/ @CpuID @fcheung

**Comment by CpuID** [comment]
Haven't had time to look into this at the moment.

One thing this would also be good for - https://aws.amazon.com/releasenotes/CloudFront/3938025103576723 (Origin Path)

**Comment by johnnyshields** [comment]
I've started work on this at #262. I can authenticate but I'm getting an XML-related error. Perhaps a seasoned Fog veteran can help?
