### ISSUE TITLE
EXCON_DEBUG and DEBUG env variables do not help debug -S key issues

### ISSUE THREAD

**Issue by h4ck3rm1k3** [fog/fog-aws#177]
EXCON_DEBUG and DEBUG env variables do not display anything on the keys not being found.

**Comment by geemus** [comment]
I'm not sure I follow what you mean related to keys and or `-S`, could you give a more concrete example? Thanks!

**Comment by h4ck3rm1k3** [comment]
yes, if you give a key that does not exist, there is no message in the debug message. I had to use strace to figure out the problem.

**Comment by geemus** [comment]
Could you give an example of what keys you were including (and how you were including them) that resulted in this? I'm still unclear on if the keys were provided to the request or in the env, etc, so I think that could help clarify. Basically a view of what you did and an example of what you would have expected would really help me nail this down. Thanks!
