### ISSUE TITLE
AWS Launch Configuration missing Ebs.Volume_Type

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#18]
Original issue at: fog/fog#3021

The AWS Autoscaling Launch Configuration object is missing the volume type attribute for creating and describing. It should be part of the block_device_mappings.

**Comment by plribeiro3000** [comment]
cc/ @jperry

**Comment by fcheung** [comment]
I think this can be closed, now that #35 has been merged

**Comment by plribeiro3000** [comment]
Thx @fcheung! Closing it.

@jperry Comment if you still have this error.

**Comment by geemus** [comment]
Thanks!
