### ISSUE TITLE
EBS create volume io1 or gp2

### ISSUE THREAD

**Issue by mg03** [fog/fog-aws#186]
I am trying to create an ebs volume from a snapshot of an encyrpted disk, like so

vol = compute.create_volume("us-east-1a", "2000", "snap-xxxxxx")

It fails with message : Volume of 2000GiB is too large for volume type standard; maximum is 1024GiB

How can i specify io1 or gp2 type along with snapshot id and 2000Gb volume size

**Comment by geemus** [comment]
If you update to the latest (if you aren't already) you should get a warning about passing a string snapshot, the 3rd argument is now a hash, which can include `SnapshotId' => ...` . It can also take `VolumeType` in the same hash. I think the specific docs around the method could use an update (we would certainly welcome any help there), but I don't see any reason to think it wouldn't pass through the args correctly.

**Comment by geemus** [comment]
Closing as I think this was resolved in old updates.
