### ISSUE TITLE
Support an IAM list_attached_role_policies method

### ISSUE THREAD

**Issue by ljohnston** [fog/fog-aws#191]
Currently IAM support allows attaching and detaching role policies. Unfortunately, if all I have is a role and I want to detach all of its role policies, as far as I can tell, there is no way to determine the list of role policies to detach.

Maybe there currently exists some other mechanism to get to the role policies attached to a role, but if there is, I can't find it.

Seems something like the following...
```
list_attached_role_policies(role_name, options={})
```
... would be required.

**Comment by geemus** [comment]
Closed by #274
