### ISSUE TITLE
compute.servers (via DescribeInstances) does not include tags reliably

### ISSUE THREAD

**Issue by bwalding** [fog/fog-aws#192]
I have an intermittent problem where the response from `compute.servers` returns our servers, but there are no "tags" filled in.  I am unable to force this to happen, but it appears to randomly occur around 1 in 10 runs (in us-east-1).

There are no errors thrown by the `compute.servers` call.

I have added `EXCON_DEBUG`, but this does not show the response body - which is what I assume would narrow this to an Amazon or Fog or Excon issue - as such I'm starting here because I'm "using" fog.

If anyone has seen this, or has any advice on how to isolate the problem it would be appreciated.

We have software that takes actions based on the presence of tags - when the list comes back empty bad things happen. If it errored, that would be fine.

**Comment by geemus** [comment]
Bizarre. Are all the calls happening from the same machine? Any chance there are different fog versions on different machines or something to that effect? You may be able to get more detailed output by setting up an excon instrumentor (instead of just the debug stuff).

**Comment by shaiguitar** [comment]
@bwalding It's possible this is an amazon side caching problem?
