### ISSUE TITLE
Fog::AWS::ELB::InvalidConfigurationRequest: policy cannot be enabled

### ISSUE THREAD

**Issue by FestivalBobcats** [fog/fog-aws#193]
Hi, I'm running Fog 1.35.0, and Fog::AWS 0.7.6.

I cannot seem to attach a policy to a listener on a load balancer:

```ruby
elb = service.load_balancers.get('test') # newly created

policy = elb.policies.create id: 'proxy-policy-test',
                             type_name: 'ProxyProtocolPolicyType',
                             policy_attributes: {'ProxyProtocol' => true})

elb.set_listener_policy(80, policy.id)

=> Fog::AWS::ELB::InvalidConfigurationRequest: proxy-policy-test cannot be enabled
```

Just attempting to apply the policy to the default HTTP listener on the ELB. It has not worked for other ports either, though I have not tried other policy types.

Has anyone seen anything like this?

**Comment by geemus** [comment]
@mikehale any chance you know a bit more about this (or could tell me a different person to ask). Thanks!

**Comment by FestivalBobcats** [comment]
So, this is what ended up solving my problem. Maybe I was doing something wrong?

```ruby
@fog.set_load_balancer_policies_for_backend_server(elb.id, 80, [policy.id])
```

**Comment by geemus** [comment]
@FestivalBobcats thanks for the update. Afraid I lack the familiarity to say, but glad you found a fix.
