### ISSUE TITLE
Support S3 auto-expiring files?

### ISSUE THREAD

**Issue by dimitko** [fog/fog-aws#194]
Hello,

Recently we're trying to make use of Amazon S3's automatic file expiration mechanism while using Fog. [1] [2]

I was unable to find something substantial anywhere, including StackOverflow. Is this supported by Fog? If not, is there a way for us to use the lower-level S3-specific objects inside Fog so we can directly hit the S3 API? I'm a newcomer to Fog's source so excuse me if these questions are naive.

It basically boils down to being able to specify how much days since the moment of uploading must the file expire, or specify an exact date -- in which case the file is gonna get deleted at this date at 00:00:00 UTC (as per Amazon's docs [3]).

The "expires" key when using <directory>.files.create(...) is only setting a metadata field in the S3 UI and I have confirmed that the files are *not* deleted at or past the UNIX timestamp specified there.

[1] https://forums.aws.amazon.com/ann.jspa?annID=1303
[2] https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html
[3] http://s3browser.com/amazon-s3-object-expiration.aspx

**Comment by dimitko** [comment]
Related, back from 2012 -- https://github.com/fog/fog/issues/698.

**Comment by geemus** [comment]
I don't have experience with this myself, but I think you may be able to get what you want using: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/put_bucket_lifecycle.rb (which specifies lifecyle rules across the bucket). Does that help?

**Comment by dimitko** [comment]
Sorry it took me a while to validate this, because even though I gave one day expiration to several files, Amazon still took its sweet time before deleting them.

I can confirm your recommendation led to a successful solution. Leaving template code for reference:

```
conn = Fog::Storage.new(provider: 'AWS', aws_access_key_id: APP_CONFIG['S3_ACCESS_KEY'], aws_secret_access_key: APP_CONFIG['S3_SECRET_KEY'])
...
lfc = {
  "Rules" => [
    {
      "ID" => "#{filename}_expiration",
      "Prefix" => "#{dir_name}/#{filename}",
      "Enabled" => true,
      "Expiration" => {
        "Days" => 30
      }
    }
  ]
}
conn.put_bucket_lifecycle(bucket_name, lfc)
...

As a side effect, I am noticing the lifecycle rule itself does *not* get deleted, but that's not Fog's fault.

**Comment by geemus** [comment]
Great to hear. We would certainly welcome any help around documentation you might have to offer given your experience. Thanks!
