### ISSUE TITLE
SQS API version is outdated

### ISSUE THREAD

**Issue by mhuggins** [fog/fog-aws#198]
The API version of SQS used by fog-aws is "2009-02-01".  This means that features relying on more recent versions (such as [long-polling](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html) on version "2012-11-05") cannot be used.

**Comment by geemus** [comment]
We usually just update when people need it, so this may well be that time. Would you be interested in updating that and doing some testing to help us move in that direction? Thanks!
