### ISSUE TITLE
using/testing on ruby 1.9

### ISSUE THREAD

**Issue by craiggenner** [fog/fog-aws#203]
To get this to usable and run the tests I had to add the following:

`spec.add_development_dependency 'mime-types', '~> 2.6.2'`

to `fog-aws.gemspec`

What do people think of adding this?  It might also be the fix for ruby 1.8, but I haven't tested yet.

**Comment by geemus** [comment]
Yeah, I think we need to lock to < 3 anyway. That said, we probably need to do it in fog-core instead (so that it will be true for all the fog sub-libraries. I'll look at doing it over there shortly.
