### ISSUE TITLE
Is there any way to skip object level `acl` setting while `public` option is true

### ISSUE THREAD

**Issue by yanke-guo** [fog/fog-aws#207]
I've set up bucket level `acl` to private, and add a policy to allow anonymous read from specified HTTP Referer header.

Now I have a problem, if I set `public` option to false, all urls will be signed, that is a waste, but if I set `public` to true, fog will add object level `public-read` `acl`, which will override HTTP Referer policy.

To solve this I have to write two policies

First, a `Allow` policy to allow anonymous read from my site.
Second, a `Deny` policy to disable anonymous read outside of my site, with IAM user permitted.

Like this https://gist.github.com/yanke-guo/38d023f984330760d2ae

**Comment by geemus** [comment]
I think what you describe is probably your best bet. The `public` option is meant to make it easy in the trivial/simple case, but is not really sufficiently powerful to capture more complicated cases such as yours.
