### ISSUE TITLE
Already initialized constant warnings

### ISSUE THREAD

**Issue by thomasfedb** [fog/fog-aws#212]
Hey, we use Fog::Aws in Carrierwave, and we've noticed some Ruby warning in our spec output that we've traced back to Fog::Aws, as follows:

```
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:6 warning: already initialized constant COMPLIANT_BUCKET_NAMES
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:8 warning: already initialized constant DEFAULT_REGION
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:10 warning: already initialized constant DEFAULT_SCHEME
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:11 warning: already initialized constant DEFAULT_SCHEME_PORT
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:16 warning: already initialized constant VALID_QUERY_KEY
```

Would it be possible to get these resolved?

**Comment by geemus** [comment]
Hmm. Nothing obviously wrong in the storage file itself. Perhaps it is being required a second time. Is there any other stack/surrounding info you could share that might help me narrow down where that might be coming from?

**Comment by thomasfedb** [comment]
Hey @geemus, this error occurs when we run our specs for carrierwave, and only occurs on JRuby. I haven't done a lot of investigation from our end yet.

There's no trace produces in the output, although I can probably set some JRuby flag to get a trace.

**Comment by geemus** [comment]
Got it. I'd be happy to fix it, just not sure where it is coming from. They are only defined the once, so I'm guessing the file gets required/loaded twice, but not certain.
