### ISSUE TITLE
Generates wrong url when region is not DEFAULT_REGION

### ISSUE THREAD

**Issue by mrudult** [fog/fog-aws#214]
```
config.fog_credentials = {
    # Configuration for Amazon S3
    :provider              => 'AWS',
    :aws_access_key_id     => AWS_CONFIG['accessKeyId'],
    :aws_secret_access_key => AWS_CONFIG['secretAccessKey'],
    :region                => AWS_CONFIG['region']
  }
```

With this config, the url generated is:

```
"https://my-bucket.s3.amazonaws.com/file.png" 
```

It should be

```
"https://my-bucket.s3-{region}.amazonaws.com/file.png" 
```

For example with `region = ap-southeast-1` I get `https://my-bucket.s3.amazonaws.com/file.png` instead of `https://my-bucket.s3-ap-southeast-1.amazonaws.com/file.png`

I'm able to temporarily fix this by setting endpoint as `https://my-bucket.s3-{region}.amazonaws.com` but in this case the url generated is `https://my-bucket.s3-{region}.amazonaws.com/my-bucket/file.png`. 

I wonder if this is the correct way to do it or the region should automatically set the correct server name.

What's the correct config? Also what are `host` and `endpoint` options in the fog_credentials hash anyway?

**Comment by geemus** [comment]
Could you share a quick example of how you are generating the urls also? Just want to make sure I'm on the same page. Thanks!

**Comment by christopherlai** [comment]
@geemus: I believe I am having the same issue when using Fog in a Rails test.

```
# config/initializers/carrierwave.rb
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider: 'AWS',
    aws_access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
    region:  ENV.fetch('AWS_REGION') # Region is us-west-1
  }
  config.fog_directory = ENV.fetch('AWS_S3_BUCKET_NAME')
  config.fog_public = false
end
```

```
# ActionDispatch::IntegrationTest
def setup
    Fog.mock!
    connection = Fog::Storage.new(
      provider: 'AWS',
      aws_access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      aws_secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
      region: ENV.fetch('AWS_REGION')
    )
    connection.directories.create(key: ENV.fetch('AWS_S3_BUCKET_NAME'))
```

This generates the following error in the console at test runtime.

```
[fog][WARNING] Your region 'us-west-1' does not match the default region 'us-east-1'
```

**Comment by geemus** [comment]
I think the issue comes from carrierwaves implementation around this: https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L332 (which I wrote, but ages ago). It looks as though you could set `endpoint` in the fog credentials to the region and it would work. I could imagine tweaking the code I linked to in order to automatically accommodate region setting, but I'm afraid it isn't something I have bandwidth for (happy to help/discuss though). Hope that helps.

**Comment by jthinlay** [comment]
I have same problem and I need help.
I've spend whole day try to solved this problem. I solved half way but I couldn't fix the rest. I'm practicing to upload images utilizing Rails framework and deploy the site to Heroku and store images to S3 Amazonaws.

I'm able to store the image to S3 but Heroku doesn't display the image on website.

I noted that S3 Amazonaws and Heroku image display not same Links.

S3 stored the image under this link:

https://s3-us-west-1.amazonaws.com/pictures333/pins/images/000/000/024/original/S.Newman__A_Place_of_Inspiration__2017__Oil_on_Canvas__36x48___3500.jpg https://momo333.herokuapp.com/pins/29

Heroku website displays the image under this link:

https://s3.amazonaws.com/pictures333/pins/images/000/000/030/medium/S.Newman__A_Place_of_Inspiration__2017__Oil_on_Canvas__36x48___3500.jpg?1511148393"

In inspector I tested by adding the aws-region part '-us-west-1' between the 's3' and 'amazonaws' and it displays the image.

However, I am not sure how I should modify the links permanently either from S3 Amazon or in my Rails code.

**Comment by geemus** [comment]
@jthinlay you should be able to change the configuration you are passing to fog (which includes your credentials) to include the region as well, which should produce the correct urls.
