### ISSUE TITLE
Long format of aws resources

### ISSUE THREAD

**Issue by nilroy** [fog/fog-aws#216]
AWS is going to change to longer id formats. Does it affect this library by any ways? @geemus 

https://aws.amazon.com/ec2/faqs/#longer-ids

**Comment by geemus** [comment]
Great question. Not that I'm aware of. I think we pass the ids through directly and when getting them back it is all based on parsing what is in between xml tags. I'll definitely keep an eye out, but I think we should be safe and in the clear.
