### ISSUE TITLE
ECS service_update does not support "deploymentConfig"

### ISSUE THREAD

**Issue by jhoffner** [fog/fog-aws#234]
Including the following configuration within the create/update_service configuration 

```
"deploymentConfig" => {
    'maximumPercent' => 100,
    'minimumHealthyPercent' => 25
}

```

throws a `MalformedInput => Unexpected complex element termination (Fog::AWS::ECS::Error)` error. 

See http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html

**Comment by geemus** [comment]
Good catch, I think this must have just been overlooked at implementation time. AWS expects a particular encoding style for nested stuff that isn't used in these calls. I think if we update to delete the value of that key and if there was a value use serialize_keys to put it back in the right format, we should be good to go. We should probably also add this parameter to the documented ones in those two requests. You can see an example of the delete/reformat/add that I mentioned here: https://github.com/fog/fog-aws/blob/27ec738ffea05beb0562f6097bd3bd6f8e2ff61f/lib/fog/aws/requests/beanstalk/create_configuration_template.rb#L35. Would you be up for patching that for us? Thanks!
