### ISSUE TITLE
CHANGELOG.md is out of date

### ISSUE THREAD

**Issue by dcarral** [fog/fog-aws#235]
Current gem's version is v0.9.1(bumped in [this commit](https://github.com/fog/fog-aws/commit/a1951a7da02705dd8ad43c40936a27a13d9136d7) from March 2016). 

Last version documented in [CHANGELOG.md](https://github.com/fog/fog-aws/blob/master/CHANGELOG.md) is v0.7.6 (August, 2015).

**Comment by lanej** [comment]
@dcarral thanks for the heads up

**Comment by dcarral** [comment]
;) Thanks Josh!
