### ISSUE TITLE
Fog Mock doesn't update

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#236]
Hello,

On rails, I want to test my method who use fog, so, I mock fog to set up the environment.

When I create a server, create a volume then attach it to server, server doesn't get updated.

block_device_mapping stays empty, I cannot list all volumes from the server.

Have I done something wrong?

``` ruby
require 'fog'
require 'test/unit'

class MyTest < Test::Unit::TestCase
  def test_volume
    Fog.mock!

    fogc = Fog::Compute.new({
      provider: 'AWS',
      region: 'eu-west-1',
      aws_access_key_id: 'foo',
      aws_secret_access_key: 'bar'
    })

    vm = fogc.servers.create({
      name: 'fogtest',
      image_name: 'ami-8cea48ff',
      machine_type: 't1.micro',
      zone_name: 'eu-west-1'
    })
    vm.wait_for { ready? }

    # creating and attaching volume
    vol = fogc.volumes.create(availability_zone: 'eu-west-1', size: 1)
    vol.wait_for { ready? }
    fogc.attach_volume(vm.id, vol.id, '/dev/sdi')
    vol.wait_for { state == 'in-use' }

    # volume exists and is attached
    vol.reload
    assert_not_nil vol.server_id
    assert_equal 'in-use', vol.state

    # vm should have this volume listed
    vm.reload
    assert_not_empty vm.block_device_mapping
  end
end
```

Original issue opened by @alex-lairan at fog/fog#3819

**Comment by shaiguitar** [comment]
Did you run that against local fog-aws and put some debug info in https://github.com/fog/fog-aws/blob/27ec738ffea05beb0562f6097bd3bd6f8e2ff61f/lib/fog/aws/requests/compute/register_image.rb#L67 ? (you can override your project's fog-aws using something like: `gem 'fog-aws', path: "~/p/your/fog-aws"` in your local Gemfile)
