### ISSUE TITLE
Tags server creation in Mock vs Real

### ISSUE THREAD

**Issue by shaiguitar** [fog/fog-aws#239]
It looks like it takes a long time using `Fog.servers.create({tags: {...}})` vs using simply `Fog.servers.create({...})` w/out tags, in mocked mode. The reason seems to be this bit of code:

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/servers.rb#L163-L165

```
            # expect eventual consistency
            if (tags = server.tags) && tags.size > 0
              Fog.wait_for { server.reload rescue nil }
...
```

If I remove the Fog.wait_for while I'm running specs/mocked mode, it will fail because the server.reload ( https://github.com/fog/fog-core/blob/master/lib/fog/core/model.rb#L39-L43 ) is indeed necessary. This is definitely true if we weren't in mocked mode.

However, is it really necessary to have this "sleep for 3 seconds" side effect when creating servers with tags in fake mode? I'm making a cluster of three mocked servers with tags and one test takes about 9 seconds just to setup. I'm not entirely sure why the `server.reload` bit isn't coming back instantaneously considering this is all happening in memory. Using benchmark I can see each `wait_for{}` iteration is taking about 3 seconds:

```
              require 'benchmark'
              Benchmark.bm do |x|
                x.report {
                  Fog.wait_for {
                    server.reload rescue nil
                  }
                }
              end
```

This will return:

``````

Shai Rosenfeld [6:01 PM] 
```shai@adsk-lappy ... $ time rspec -c spec/using_fog_mocks.rb --backtrace
Run options: include {:locations=>{"./spec/using_fog_mocks.rb"}}
       user     system      total        real
   0.000000   0.000000   0.000000 (  3.012020)
       user     system      total        real
   0.000000   0.000000   0.000000 (  3.008882)
       user     system      total        real
   0.000000   0.000000   0.000000 (  3.011893)
       user     system      total        real
   0.000000   0.000000   0.000000 (  3.011872)
       user     system      total        real
   0.000000   0.000000   0.000000 (  3.010188)
``````

Happy to help, assuming this isn't intentional, but I'll need some pointers because I'm not sure why it's not just returning immediately vs reloading objects from memory...

Thoughts/Halp?

**Comment by geemus** [comment]
wait_for has exponential backoff, so if it isn't true on the first try it would wait a bit before trying again. This (broadly speaking) was intentional as not paying attention to timing can cause issues in the real world. You can tweak the waited-times down though, which is what we used to do on things we were more confident about. I think you can tweak it using `Fog.interval = 1` or even `Fog.interval = 0` if you want to skip this behavior.

**Comment by shaiguitar** [comment]
With tweaking `Fog.interval` it looks like it takes at the least 2 seconds for `server.reload` to return something: https://gist.github.com/shaiguitar/c801f5e25570e3ba90e1

Any ideas as to what it's actually doing in `mocking` that's taking it this long? Would be great if it would return immediately if that was the desired behavior for mocked mode / w `Fog.interval=0.1` etc.

Stated in OP the reload is reaching into this: https://github.com/fog/fog-core/blob/master/lib/fog/core/model.rb#L39-L43 - thoughts on what could be taking 2 seconds in getting the mocked data into that collection?

**Comment by geemus** [comment]
My guess is that the issue is more likely to be in aws mock stuff than fog-core, in particular maybe: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/compute/create_tags.rb#L40 (though nothing is jumping out at me).

**Comment by shaiguitar** [comment]
I think I profiled `create_tags` and it's not that. The issue isn't the creation of tags. It's the fact that `server.reload` is taking 2 seconds. Unless `Fog.wait_for` is async (readability wise it seems like a simple blocking operation) the creation of tags is done after that 2 second hang: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/servers.rb#L163-L165 

@lanej any ideas perhaps?
