### ISSUE TITLE
CloudFormation stack tags cause describe_stacks to break

### ISSUE THREAD

**Issue by jamesremuscat** [fog/fog-aws#240]
When using CloudFormation stacks, the [`DescribeStacks` API action](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStacks.html) returns a list of stacks and information about them.

This information also includes [tags](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html). However, fog does not return these tags; furthermore, _the presence of tags in the AWS API response_ breaks the response to `describe_stacks`.

This is because the `<Tags>` element of the response contains `<member>` elements. The `Fog::Parsers::AWS::CloudFormation::DescribeStacks` parser assumes that any `</member>` outside of `<Outputs>`, `<Parameters>` and `<Capabilities>` is the end of a stack description, so starts a new stack.

The net result is that a single stack in the AWS response gets turned into multiple 'stacks' in the Fog parsed result, many of which will be empty, and the `Outputs` and `Parameters` will be split across different 'stacks' (since `Tags` appears between them in the XML).

I suspect that adding support for returning tag information will solve this problem.

**Comment by geemus** [comment]
Thanks for the detailed report. We have other parsers that have to do things like this, so it should be doable. Would you be up for working on a fix with us? Thanks!
