### ISSUE TITLE
Timeouts on Compute#describe_volumes due to extreme numbers of volumes

### ISSUE THREAD

**Issue by halorgium** [fog/fog-aws#244]
The `Compute#describe_volumes` API call currently uses the `filters` parameter exclusively event when using the primary key (`volume-id`). 

The AWS EC2 API does not seem to be responsive when the number of volumes reaches large amounts. 

There is an alternative parameter (indexed `VolumeId`) which decreases the response time to a small fraction of the time when using the `filters` parameter. 

There doesn't seem to be a clear way to change/extend the API of `Compute#describe_volumes` as it only accepts the `filters` hash. 

Back in 2010, there was a significant refactor to move from queries using primary-key parameters to filters. See this [commit](https://github.com/fog/fog/commit/6f2ce0d895632e7ef2b4c5d641dfdf3e8620b46b#diff-dba55fff22bbb069d552da6132e1b7cdL29)

Any guidance on how best to contribute a change would be helpful. 

A few thoughts: 
- A new method which calls the API using the primary-key parameter. Potentially `Compute#describe_volume` (note the singular)
- Adding a key to the `filters` hash which is used to add the indexed `VolumeId` parameters. 
- Should the deprecation be removed? It is 6 years old, but our usage relies upon this API unknowingly.

**Comment by halorgium** [comment]
Regardless of the solution, there is existing infrastructure around this indexed `VolumeId` parameter. 

`Compute#describe_volume_status` uses this: 

``` ruby
params = Fog::AWS.indexed_request_param('VolumeId', filters.delete('VolumeId'))
```

**Comment by geemus** [comment]
Thanks for the detailed info. I think I had the impression that filters were the future and/or were at least more generically useful than just lookup by id, so sought to standardize there.

My inclination would be to keep accepting a hash in this method, but perhaps we should pass volume id outside of filters (at least in the case where it is a singular one, does the volume-id outside of filters work for multiple ids?) and just merge that with any other filters, so something like:

```ruby
params = Fog::AWS.indexed_request_param('VolumeId', filters.delete('VolumeId'))
params = params.merge(AWS.indexed_filters(filters))
```

It seems like that might get us both (though as I mention, it might need to limit that to the single-volume case, I'm not at all sure). Perhaps worth a try at least?

And yes, we are probably well past a reasonable inflection point to simplify and yank the old-old deprecations.
