### ISSUE TITLE
no implicit conversion of Array into String in `aws/storage.rb` from `bucket_name` in params.

### ISSUE THREAD

**Issue by wspurgin** [fog/fog-aws#246]
On line [280 of `aws/storage`](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L280) The bucket name is compared against the regex in `COMPLIANT_BUCKET_NAMES`. However, the parameters of my request (using rails 4.2.6, and carrierwave latest or v0.11) show bucket name as follows:

```
>>  params
=> {
:bucket_name=>["com-thelegalally-staging", false],
:object_name=>"blah/blah/RackMultipart20160420-58021-14t3808.jpg", :method=>"GET",
...
}
```

As you can see, the `bucket_name` in params is actually an Array... which explains the error I'm receiving. I haven't been able to track down if this is specifically a problem with `fog/aws` or because of the rails version, but I dug through the carrierwave code base, and the call is: [`local_file.url(expire_at, options)`](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L193) which is a call to `url` in `storage.rb`.

If this is more of a carrierwave thing, let me know, and I'll move this there. If there's any additional information you need, I'll do my best to get it to you.

Cheers :beers:

**Comment by lanej** [comment]
@wspurgin i would that carrierwave has an odd array expansion some where. `bucket_name` is intended to be a String only.

**Comment by wspurgin** [comment]
Could be. But carrierwave doesn't touch the request (to my knowledge). It delgates that to fog... Or so it seems. I'm going to try recreating it with a pristine rails project.

**Comment by wspurgin** [comment]
@lanej After a bit of digging around, I think I've discovered the source of the problem, and it's definitely *not* anything with Fog-AWS. Sorry for all the confusion. Sohow inside carrierwave's configure block, specifying `config.fog_directory = ENV.fetch("S3_BUCKET", "some_default")` causes carrierwave to evaluate the `ENV` fetch as `["whatever-the-actual-value-is", false]` Which produces the problem I found. It has to do with how they evaluate the value (since everything is done rather dynamically with their configuration). Even something like `{}[:foo] || "some_default"` produces `["some_default", false]`... I'll take up the issue with them, sorry to create a bad issue 😞

Thanks again for the help!

**Comment by geemus** [comment]
No worries, glad you found a fix!

**Comment by omgreenfield** [comment]
I hope this helps someone.

Take a look at the line where the `fog_directory` is being set
```
config.fog_directory = 'my_bucket_name',
```

See that comma at the end? It turns it into an array.

Easy mistake to make when the `fog_credentials` bit is set to an object which requires commas at the end of every line.

**Comment by geemus** [comment]
@omgreenfield Thanks for sharing that, although I'm not sure what context you are pointing to for that code snippet. Just let me know if you think there is something we could clarify or improve to make this problem less likely.

**Comment by omgreenfield** [comment]
Good call. I foolishly just copy/pasted my statement on a few different threads.

If this problem was the same as mine (which I believe it is), it stems from an initializer where `CarrierWave` configurations are set. It might look like this:

```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider:              'AWS',
    aws_access_key_id:     SOME_ACCESS_ID,
    aws_secret_access_key: SOME_ACCESS_KEY,
    region:                SOME_REGION,
  }
  config.fog_directory  = SOME_BUCKET
end
```

When adding commas to the end of the lines for the `fog_credentials` object, I also put a comma after `SOME_BUCKET`, making `config.fog_directory` an array instead of a string.

'Twas very hard to debug.

**Comment by geemus** [comment]
@omgreenfield Yikes, that would definitely be a pain to debug. Thanks for the additional context, that makes more sense now, I had been a little lost from the original comment but this brought it all together.
