### ISSUE TITLE
Bump fog-core to >=1.38.0

### ISSUE THREAD

**Issue by voelzmo** [fog/fog-aws#247]
To include excon 0.49.0 we need fog-core >=1.38.0. Can we please get a bump to fix https://github.com/excon/excon/issues/542 as described in https://github.com/fog/fog-core/issues/184?

Thanks!

**Comment by geemus** [comment]
1.38.0 should be compatible with the ~> here, so I think they should work together if you update stuff. I'll bump as well though.

**Comment by geemus** [comment]
closed by https://github.com/fog/fog-aws/commit/5e6f7fd085216ce0604e3e7a7bf93c09ef5d0f57
