### ISSUE TITLE
Support Amazon S3 Transfer Acceleration

### ISSUE THREAD

**Issue by natematykiewicz** [fog/fog-aws#250]
https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

**Comment by geemus** [comment]
Sounds good, would you be up for working on a pull request around adding this? Thanks!

**Comment by joepestro** [comment]
I was about to add this, but after looking through it, it doesn't seem like any library changes would be necessary to generate accelerated URLs for s3. 

Here's how fog is generating s3 URLs:

```
def region_to_host(region=nil)
  case region.to_s
  when DEFAULT_REGION, ''
    's3.amazonaws.com'
  when 'cn-north-1'
    's3.cn-north-1.amazonaws.com.cn'
  else
    "s3-#{region}.amazonaws.com"
  end
end
```

Here's how the AWS docs say to specify to enable accelerated URLs:

```
bucketname.s3-accelerate.amazonaws.com
```

So specifying "accelerate" as `region` when initializing fog should do the trick: 

```
Fog::Storage.new({
  provider:               'AWS',
  region:                 'accelerate',
  aws_access_key_id:      AWS_ACCESS_KEY_ID,
  aws_secret_access_key:  AWS_SECRET_ACCESS_KEY
})
```

**Comment by natematykiewicz** [comment]
Oh, wow. That sure does seem like that's all it would take!

**Comment by geemus** [comment]
Nice, thanks for the work-around.

Though this happens to work now, it isn't very obvious and I fear it could accidentally get broken pretty easily. Any thoughts on how we might make it clearer and more explicit to avoid that? Thanks!

**Comment by natematykiewicz** [comment]
> You can use all of the Amazon S3 operations through the transaction acceleration endpoint, except for the following the operations: GET Service (list buckets), PUT Bucket (create bucket), and DELETE Bucket. Also, Amazon S3 Transfer Acceleration does not support cross region copies using PUT Object - Copy.

Since not ALL endpoints can work like that, a proper solution would probably be to add a boolean to the config (maybe accelerate: true), and then use the accelerate "region" for supported endpoints and the actual region for those few that don't work with acceleration.

**Comment by MatthiasRMS** [comment]
Any progress on this ?

**Comment by geemus** [comment]
None that I'm aware of.

**Comment by NARKOZ** [comment]
Support for acceleration was added in https://github.com/fog/fog-aws/pull/505
