### ISSUE TITLE
Auto Scaling Group does not enable metrics

### ISSUE THREAD

**Issue by MrPrimate** [fog/fog-aws#251]
I'm providing the `enabled_metrics` option when creating my Auto Scaling Group.

My `options` looks something like:

```
{:id=>"euwest1-ci", :launch_configuration_name=>"euwest1-ci", :load_balancer_names=>["euwest1-ci"], :min_size=>1, :max_size=>1, :desired_capacity=>1, :availability_zones=>["eu-west-1a"], :tags=>{"Name"=>"ci"}, :health_check_grace_period=>120, :enabled_metrics=>["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupTerminatingInstances", "GroupTotalInstances"], :vpc_zone_identifier=>"subnet-000000f"}
```

I save:

```
asg = @as.groups.new( options )
asg.save
```

The ASG is created successfully, but the metrics are not enabled. I describe the asg that comes back:

```
[2016-05-03T19:12:42.176819 #10103] DEBUG -- :   <Fog::AWS::AutoScaling::Group
id="euwest1-ci-ci",
arn="arn:aws:autoscaling:eu-west-1:111111111111:autoScalingGroup:dsad3edde-dsd3-dsd34-aaf4-c771a83a065c:autoScalingGroupName/euwest1-ci",
availability_zones=["eu-west-1a"],
created_at=2016-05-03 18:12:41 UTC,
default_cooldown=300,
desired_capacity=1,
enabled_metrics=[],
health_check_grace_period=120,
health_check_type="EC2",
instances=    <Fog::AWS::AutoScaling::Instances
  [

  ]
>,
launch_configuration_name="euwest1-ci",
load_balancer_names=["euwest1-ci"],
max_size=1,
min_size=1,
placement_group=nil,
suspended_processes=[],
tags=[{"ResourceId"=>"euwest1-ci", "PropagateAtLaunch"=>true, "Value"=>"ci", "Key"=>"Name", "ResourceType"=>"auto-scaling-group"}],
termination_policies=["Default"],
vpc_zone_identifier="subnet-00000f"
```

Is this expected behaviour or is there a bug?

**Comment by geemus** [comment]
It looks as though it filters out unknown options and that for whatever reason the one you are using is not presently in the list, see: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/auto_scaling/create_auto_scaling_group.rb#L65. Would you be up for helping out by adding it (and adding some details to the documentation block at the top about the parameter)? Thanks!

**Comment by lanej** [comment]
It doesn't appear that [CreateAutoScalingGroup](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CreateAutoScalingGroup.html) supports creating AND enabling metrics at the same time.

@geemus maybe an `ArgumentError` when unsupported keys are passed ?

**Comment by lanej** [comment]
or a warning

**Comment by geemus** [comment]
Ah, oops. Yeah, at least a warning seems like a good plan. Silently dropping them seems likely to lead to a lot of confusion such as this.

**Comment by lanej** [comment]
@MrPrimate [`enable_metrics_collection`](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/auto_scaling/group.rb#L82) is what you want for right now.

**Comment by MrPrimate** [comment]
@lanej - thanks

**Comment by MrPrimate** [comment]
FYI, for anyone else searching for this that wants a solution, I used:

    if options[:enabled_metrics]
        asg.enable_metrics_collection('1Minute', options[:enable_metrics])
    end

**Comment by geemus** [comment]
Looks like the main problem was solved, though it suggests a possible refinement (not dropping unknown stuff). Closing for now, though I would welcome an error on unknown stuff if anyone has the time/inclination.
