### ISSUE TITLE
Using STS

### ISSUE THREAD

**Issue by MrPrimate** [fog/fog-aws#253]
I'm looking for an example of using STS to assume a role and then use this state to use say Fog::Compute::AWS::Volumes.

I can initiate an STS instance, and assume a role, which in it's body returns some credentials. Do I have to pull these out and pass to Fog::Compute::AWS as a new connection, or am I missing something in how I can use the STS object returned by assume_role?

Many thanks in advance.

**Comment by neillturner** [comment]
Indeed you do. 
 you can see it in my code at: 
  https://github.com/neillturner/ec2dream/blob/master/lib/Amazon.rb
not saying it the greatest code though. -)

**Comment by geemus** [comment]
Closing as it looks like there was an answer for this.
