### ISSUE TITLE
I'd like to configure my Excon read_timeout and write_timeout 

### ISSUE THREAD

**Issue by utako** [fog/fog-aws#254]
I'd like to be able to configure the timeout on requests (specifically around Fog::Storage). I realize it's 60 seconds by default, but I'd like to make it much smaller. Ideally, I'd be able to pass a configuration hash and have it applied. Is this or something similar already implemented somewhere within fog-aws?

I'm using fog 1.37.0, fog-aws 0.9.1, and excon 0.48.0. This is tangentially related to [this issue](https://github.com/fog/fog-aws/issues/180).

Thanks.

**Comment by utako** [comment]
Ah, got it. It's set [here](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L497).

**Comment by geemus** [comment]
Glad you figured out what you needed, thanks for the update!
