### ISSUE TITLE
AWS SQS AddPermission API missing

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#26]
Original issue at: fog/fog#3375

Pretty straightforward: the AddPermission API from AWS SQS (http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html) is not available in Fog::AWS::SQS.

Is this intentional (i.e., there's some issue with it) or inadvertent? If the latter, please add.

(EDIT: RemovePermission is also missing... might as well add that one too)

**Comment by plribeiro3000** [comment]
cc/ @rcrocker

**Comment by rcrocker** [comment]
Thank you.
