### ISSUE TITLE
Alias for server side encryption not working

### ISSUE THREAD

**Issue by youreddy** [fog/fog-aws#260]
Hello, 
I am using fog-aws v0.9.1 and encountered an issue where the `encryption`option was not working when saving a file to AWS. Using `x-amz-server-side-encryption` still works. It's possible that other options that have been aliased are not setting values correctly either.

https://github.com/fog/fog-aws/blob/v0.9.1/lib/fog/aws/models/storage/file.rb#L24

Reproduction Steps: 
1. Create an unencrypted file and upload to S3
2. Use fog to update and save the file while passing in `encryption: 'AES256'`
3. Check the file's properties in S3 and notice that server-side encryption is not set
4. Use fog to update and save the file while passing in `x-amz-server-side-encryption: 'AES256'`
5. Check the file's properties in S3 and notice that server-side encryption is set to AES-256

**Comment by geemus** [comment]
It looks like the expected code is around, not sure what is not working there. In particular if encryption is set:

* It merges it into headers for the save here: https://github.com/fog/fog-aws/blob/v0.9.1/lib/fog/aws/models/storage/file.rb#L206
* Building the values out here: https://github.com/fog/fog-aws/blob/v0.9.1/lib/fog/aws/models/storage/file.rb#L281

I wonder if this is somehow just falling through the cracks there (or if the output is just slightly off and being ignored or something). ie maybe the encryption_key is set but not the right/expected value (vs the explicit set you do there which wouldn't set the key). Hope that helps narrow in on it, I don't have much explicit experience around this, so would appreciate any help/insight you might have on how best to fix this.

**Comment by youreddy** [comment]
I should be hitting this line of code https://github.com/fog/fog-aws/blob/v0.9.1/lib/fog/aws/models/storage/file.rb#L285 which sets the exact key I need to set up encryption. So I'm not sure why this is happening. This leads me to believe that there might be an issue with how the attributes are being aliased.

Any thoughts on that?

**Comment by geemus** [comment]
Could you include a code sample of how you are updating/saving/etc? Hoping that might help me see more explicitly what might be going on (whereas I fear the higher level description might miss something). Thanks!
