### ISSUE TITLE
S3: retry on 500 internal server error

### ISSUE THREAD

**Issue by mtekel** [fog/fog-aws#264]
Hi,

it doesn't seem FOG currently retries on 500 Internal Server Error S3 API response. However, according to [AWS documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html), 500 error means

> We encountered an internal error. Please try again.

It would be good it FOG would retry the request when it receives that response.

**Comment by geemus** [comment]
I believe most, if not all of these calls should have `idempotent` set, which uses the excon middleware to retry 3 times for most errors as shown here: https://github.com/excon/excon/blob/f189c0bc1658ca1822556764f581216c07316922/lib/excon/middlewares/idempotent.rb

So, I would expect a retry to occur unless it fails multiple times in a short period (or if there are some commands that idempotent got left out on for some reason). Are there particular commands you are seeing this with?

**Comment by mtekel** [comment]
Hi,

we have been impacted by this once so far (or once that we know of). In the investigation we have discovered that AWS recommends to retry, but FOG currently doesn't. We have not been impacted by 503 (...that we know of), but realised it's the same case as with 500, so we opened #265 ...

If setting `idempotent` for these calls fixes the issue (triggers retry) then it would be good if FOG implemented that.

**Comment by geemus** [comment]
I think all (or at least most) of the storage/S3 related requests already have idempotent set. I would expect that they will already retry successfully unless it actually fails 4 times in a row, unless there are particular requests we somehow missed for idempotence (but there aren't any that I know of). So if you can narrow down the case in which you were seeing the issue that could be helpful in terms of finding an outlier, if there is in fact one. Otherwise, it may actually have multiple failures in a short time. For that case you could change options to retry more times. Right now it also tries to retry quickly, and perhaps it should have a backoff (as if there is a real issue, it may fail several times in a row before working again some time later).

**Comment by mtekel** [comment]
We don't use FOG directly. It is used by Cloud Controller of Cloud Foundry, where we got the error. We could not see repeated errors in the logs. The final (only) error message in the logs was from excon, meaning excon errors were able to propagate through FOG and CC to logs:
```
excon.error.response
  :body          => ""
  :headers       => {
    "Connection"        => "close"
    "Content-Type"      => "application/xml"
    "Date"              => "Fri, 24 Jun 2016 18:00:12 GMT"
    "Server"            => "AmazonS3"
    "Transfer-Encoding" => "chunked"
    "x-amz-id-2"        => "<amazonID>"
    "x-amz-request-id"  => "<requestID>"
  }
  :host          => "ourbucket.s3-eu-west-1.amazonaws.com"
  :local_address => "1.2.3.4"
  :local_port    => 53641
  :path          => "/a/b/c/d-e-f-g/h"
  :port          => 443
  :reason_phrase => "Internal Server Error"
  :remote_ip     => "54.231.140.1"
  :status        => 500
  :status_line   => "HTTP/1.1 500 Internal Server Error\r\n"
```

I could not really tell if excon was retrying the request. Nevertheless given the size/capacity of AWS S3 service, it's quite unlikely that if you hit it 3 times, you always hit the same server with same internal server error (that would mean whole service had some issue. We're seeing this kind of error approximately once-twice per week). On the other side, I am not sure how excon does retry - e.g. it could be still using the same connection to the same server. In that case it would be desirable to retry on FOG side, making a new connection (with new DNS resolution) explicitly.

**Comment by geemus** [comment]
Hmm, yeah the indirection through a library certainly makes this harder. I think we should be able to tell pretty concretely if there are retries if we use debug/instrumentor output (which it looks like you are already getting there). You should be able to see a `retries_remaining` value that would decrement across the failures I think. Sorry I haven't been able to pin this down more directly, a good number of people use fog/s3 and I haven't heard of this issue before, so trying to figure out what makes this case exceptional. Thanks.
