### ISSUE TITLE
S3: retry on 503 Service Unavailable

### ISSUE THREAD

**Issue by mtekel** [fog/fog-aws#265]
Hi,

it doesn't seem FOG currently retries on 503 ServiceUnavailable or 503 SlowDown Errors in S3 API response. However, according to [AWS documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html), these errors mean that retry rate should be reduced
> Reduce your request rate.	

In order to do that, there should be retry implemented at first. It would be good if FOG implemented some conservative retry on these kinds of responses.

**Comment by geemus** [comment]
closing in favor of #264 (I suspect they will have the same solution at this point anyway, so avoiding some duplication).
