### ISSUE TITLE
Feature: Access logs for ELB

### ISSUE THREAD

**Issue by lockstone** [fog/fog-aws#271]
A little over two years ago, AWS added the ability to send access logs from an ELB to an S3 bucket. It appears that this feature is not available in fog, is that correct? I see a comment concerning it here:

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/elb/modify_load_balancer_attributes.rb#L14

Just wondering if this is actively under development or still a needed feature. Thanks!

**Comment by geemus** [comment]
@lockstone There is no in-progress work around this that I'm aware of, most development here tends to occur when somebody needs some feature in particular (so perhaps nobody else needed this just yet). Certainly happy to provide guidance should you want to work on this. Thanks!

**Comment by geemus** [comment]
oops, didn't mean to close, one too many tab presses before submitting

**Comment by lockstone** [comment]
Thanks @geemus. I certainly wouldn't mind implementing it. But no time right now and, I guess like everyone else, this isn't high priority for us, just a "nice to have." But thanks for confirmation that it's an open issue and needs work.
