### ISSUE TITLE
Feature: Custom Managed Policies

### ISSUE THREAD

**Issue by MrPrimate** [fog/fog-aws#272]
I would like support to update Custom Managed IAM Policies.

`create_policy` can create policies, however the policy model expects a user or group policy, and no support for updating policy/updating policy version with CreatePolicyVersion API call.

**Comment by geemus** [comment]
Sounds good. Could you sketch out what you imagine the end result would look like and/or how it would work? Hopefully we can reach some consensus there before getting too far into code and it can guide the implementation. Thanks!

**Comment by geemus** [comment]
oops, accidental close, just meant to comment

**Comment by MrPrimate** [comment]
I think IAM requests to CreatePolicyVersion to create a new policy version, SetDefaultPolicyVersion to set a default policy, and DeletePolicyVersion to delete a policy version would allow full manipulation of Custom Managed IAM Policies.

I'm not quite sure how to work it into the model though.

**Comment by geemus** [comment]
I'm afraid I don't have a lot of familiarity with this space, so I'm happy to listen and discuss but not sure I have much to offer without help.

**Comment by MrPrimate** [comment]
@geemus, I think something like https://github.com/fog/fog-aws/pull/274, although I think I will need assistance with the tests. Thanks.

**Comment by geemus** [comment]
Awesome. I'm going to go ahead and close this in favor of consolidating discussion on #274.
