### ISSUE TITLE
Chunked images response causing Nokogiri::XML::SyntaxError

### ISSUE THREAD

**Issue by kensoncheung** [fog/fog-aws#273]
Hi there,

  I'm having issue in using fog-aws gem to list OS images from AWS, where the images owner are AWS.
  This does not happen regularly, but happening more frequently recently.

  I tried to add debugger to track it and found out that it seems due to parsing chunked XML result.
  I had tried to extend the chunk size to original one times 10240, however it still happens.

  Is there any suggested way to call the describe_images in order to prevent the above issue?

  Here are the related gems I use:
- fog-core (1.40.1)
- fog-aws (0.9.4)
- fog-xml (0.1.2)
- excon (0.49.0)
- nokogiri (1.6.6.2)

Backtrace:

```
XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `write'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:31:in `block in request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/response.rb:118:in `call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/response.rb:118:in `parse'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/docker-api-1.26.2/lib/excon/middlewares/hijack.rb:45:in `response_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:389:in `response'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:253:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-aws-0.9.4/lib/fog/aws/compute.rb:525:in `_request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-aws-0.9.4/lib/fog/aws/compute.rb:520:in `request'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-aws-0.9.4/lib/fog/aws/requests/compute/describe_images.rb:49:in `describe_images'
/home/kensoncheung/.rvm/gems/ruby-2.1.2@myproj/gems/fog-aws-0.9.4/lib/fog/aws/models/compute/images.rb:46:in `all'
```

**Comment by geemus** [comment]
Sorry to hear you are having trouble, this is my first knowledge of this particular bug. Could you provide a bit more info about how you are using this and the cases where it is erroring? In particular if you have a small code block that can reproduce the error it would make it much easier to get this fixed. Also, does it error for the same credentials or different ones? Anything else that you think might be helpful or relevant? Thanks!

**Comment by kensoncheung** [comment]
@geemus, 

Thanks for your quick response!

I've written a method to query a list of public OS images owned by AWS with several filters applied.

I believe that the image list might be huge and thus causing the chunked issue.

This is not regularly reproducible. However, it does occur randomly when I try to use this method in a cron job. Everytime it failed, it failed on Nokogiri with parsing issue on different XML nodes.

e.g.
- Couldn't find end of Start Tag devi (Nokogiri::XML::SyntaxError)
- StartTag: invalid element name (Nokogiri::XML::SyntaxError)
- Opening and ending tag mismatch: virtualName line 0 and v (Nokogiri::XML::SyntaxError)

BTW, I used an AWS global account for testing, but it does happen before when I use china account as well. 
Below is the snippet, to rescue this issue, I added a retry there (commented out in snippet below), but sometimes it success once retry but sometimes it still failed after 5 times retry.

```
    def list_images
      if @cloud.options[:endpoint_code] == "china"
        owners = [
          { 'Owner' => 'amazon' }, # amazon linux, windows, sles
          { 'owner-id' => '837727238323' }, # ubuntu
          { 'owner-id' => '841258680906' } # redhat
        ]
      else
        owners = [
          { 'Owner' => 'amazon' }, # amazon linux, windows, sles
          { 'owner-id' => '099720109477' }, # ubuntu
          { 'owner-id' => '309956199498' }, # redhat
          { 'owner-id' => '595879546273' } # coreos
        ]
      end
      filter = {
        'image-type' => 'machine',
        'root-device-type' => 'ebs',
        'architecture' => 'x86_64',
        'ExecutableBy' => 'all'
      }
      owners.map { |o| o.merge(filter) }.map do |image_filter|
        # retries = 0
        # begin
          @cloud.connection.images.all(image_filter)
        # rescue Excon::Errors::SocketError => e
        #   if retries < 3 && e.message.index("XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)")
        #     applog :warn, "Retry due to #{e.message}"
        #     retries += 1
        #     retry
        #   else
        #     raise
        #   end
        # end
      end.flatten
      end.flatten
    rescue => ex
      applog :error, ex
      raise
    end
```

**Comment by geemus** [comment]
Thanks for the extra info, I don't think I'm going to be able to get to this very soon unfortunately, so wanted to share a bit of extra info. If you comment out the parser on the request, you should get back the full/raw response without errors. This might provide more insight into stuff, especially if compared against those particular errors (although if it is intermittent you don't know for sure if it is a repro-case). Anyway, it would let you skip the parser and get the stuff back (which you could perhaps do your own parsing on if you really need to. In any event, I'll try to revist, just unlikely to be very soon I fear.

**Comment by kensoncheung** [comment]
Hi @geemus ,

Thanks for your reply. 

Do you mean to monkey patch describe_images, like

```
        def describe_images(filters = {})
          options = {}
          for key in ['ExecutableBy', 'ImageId', 'Owner']
            if filters.is_a?(Hash) && filters.key?(key)
              options.merge!(Fog::AWS.indexed_request_param(key, filters.delete(key)))
            end
          end
          params = Fog::AWS.indexed_filters(filters).merge!(options)
          request({
            'Action'    => 'DescribeImages',
            :idempotent => true,
            #:parser     => Fog::Parsers::Compute::AWS::DescribeImages.new
          }.merge!(params))
        end
      end
```

Then after getting the raw XML, try to parse it myself?

It's good enough if I can have a way to work around this. 
Looking forward for your future update!

**Comment by geemus** [comment]
@kensoncheung yeah, that looks like what I intended. I think that should give you raw XML, which should hopefully let you workaround and perhaps find a way to fix this as well. Thanks!

**Comment by prashantg-cuelogic** [comment]
@geemus Any updates further, today we have came across with the same problem.
we are fetching public amis from cron job we got an error as
Error Message: XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)

Thanks in advance

**Comment by geemus** [comment]
@prashantg-cuelogic We haven't pinned down anything specifically so far, I'm afraid. I would guess the format has changed and we are falling over on it, but without raw XML it's hard to know for sure.
