### ISSUE TITLE
How to setup private files with CloudFront?

### ISSUE THREAD

**Issue by betjaminrichards** [fog/fog-aws#275]
Currently I have an S3 Bucket with an access policy that only allows access from a CloudFront Origin Access Identity:

```
{
	"Version": "2012-10-17",
	"Id": "PolicyForCloudFrontPrivateContent",
	"Statement": [
		{
			"Sid": "Grant a CloudFront Origin Identity access to support private content",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXXXXXXXXX"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::my-bucket/*"
		}
	]
}
```

This should prevent any access to the S3 asset which is not through the CloudFront distribution. However when I input the S3 url into my web browser I can still access the file.

I have `config.fog_public = true` so Fog is putting a public access setting on the uploaded object.

I tried changing the setting to `config.fog_public = false` but that then started returning signed URL's that ignored my `asset_host` setting (so provided the signed S3 URL rather than the unsigned CloudFront URL).

Can you advise what is the correct way to set this up with Fog?

**Comment by geemus** [comment]
Hey, sorry to hear you are having issues. Are you using fog directly or through some other library (like carrierwave or paperclip perhaps?). Just wanting to pin down the usage patterns to try and give the best advice. I think this may have to do with a library outside of fog (as fog_public isn't a fog internal thing). I think maybe you can use fog directly to give you either signed or unsigned as you want here (but I think maybe carrierwave makes broader assumptions around what public means).

Alternatively, I suppose you could set fog_public on writes but disable it on reads? This seems potentially error prone/dangerous though.

**Comment by betjaminrichards** [comment]
Ah, sorry, you're right. I'm using it via Carrierwave. Should I post the issue there instead?

**Comment by geemus** [comment]
@betjaminrichards No problem. Posting there may be helpful as I'm not the most up to date on those details. The easiest solution may be to set public to false and then either use fog calls or build the urls manually (I forget which of those approaches carrierwave takes when public is true). It might involve a little mix-and-match though. Anyway, hopefully they can help you sort it out, but if that bogs down I can probably try to look through that code and help too. Thanks!
