### ISSUE TITLE
Disable chunked encoding

### ISSUE THREAD

**Issue by marclennox** [fog/fog-aws#285]
I'm trying to use Fog-AWS with minio, which emulates S3 storage.  Currently minio requires V4 signature format, but then don't (yet) support STREAMING-AWS4-HMAC-SHA256-PAYLOAD signature encoding.

Is there a way to force Fog not to use chunked encoding until such time as minio supports it?  Alternatively, would there be a relatively easy monkey-patch to Fog-AWS to make this work?

It's a short-term requirement as minio is working on supporting chunked encoding.

Thanks.

**Comment by geemus** [comment]
Doesn't look like there is presently an existing way to do it (you may have to monkey patch for now). It appears to be set any time you are doing v4 and body responds to read, see: https://github.com/fog/fog-aws/blob/562673d3b212a1567b133eae2aed1f449bab3db0/lib/fog/aws/storage.rb#L577

**Comment by marclennox** [comment]
That's what I figured.  For now I've come up with the following monkey patch.  It's not great, but it's very temporary.

```ruby
# config/initializers/fog_aws_storage_extensions.rb

# Temporary monkey patch of Fog AWS storage until Minio implements support for
# STREAMING-AWS4-HMAC-SHA256-PAYLOAD (https://github.com/minio/minio/issues/2326)
module FogAwsStorageExtensions
  def request(params, &block)
    params[:body] = params[:body].read if params[:body].respond_to?(:read) && (Rails.env.development? || Rails.env.test?)
    super
  end
end
module Fog
  module Storage
    class AWS
      class Real
        prepend FogAwsStorageExtensions
      end
    end
  end
end
```

**Comment by geemus** [comment]
Yeah, not ideal, but seems like it gets you what you need and hopefully they can resolve it quickly for you. Thanks for the update!
