### ISSUE TITLE
directories ignore region option

### ISSUE THREAD

**Issue by xithan** [fog/fog-aws#287]
I've just started to use fog and aws so I'm not sure how this is supposed to work but the following seems wrong to me:

``` ruby
options[:region] = 'eu-central-1' 
Fog::Storage.new(options).directories.new(key: 'test').location # => "us-east-1"
```

Shouldn't the directory use the region as location?

**Comment by geemus** [comment]
`new` just creates a local version, I think if you were to `save` and then check it would be correct and match. Still, you are probably correct that this is confusing and inaccurate. We would certainly welcome help in fixing it, and I suspect it would be a pretty easy place to contribute. Thanks!

**Comment by geemus** [comment]
Closing as I believe the question was answered.
