### ISSUE TITLE
Getting OperationAborted error on file storage operation

### ISSUE THREAD

**Issue by alexandru-calinoiu** [fog/fog-aws#288]
I am working on a migration to s3, writing the code to move all the assets now, there a lot of them that will be stored in 1 bucket. I am getting `A conflicting conditional operation is currently in progress against this resource. Please try again.`

Am I broking any limitations that I am not aware of?

**Comment by lanej** [comment]
@alexandru-calinoiu a bucket operation underway ?  https://forums.aws.amazon.com/thread.jspa?threadID=37532

**Comment by alexandru-calinoiu** [comment]
No, all the searches on the web seem to point to this bucket operations, but all I am doing is puting objects in a existing bucket.

**Comment by geemus** [comment]
Are you doing any multi-threading or processing, where more than one thing might be trying to put the same object simultaneously? That's the only case that comes to mind from what you describe, and though I haven't explicitly run into it myself it seems pretty easy to imagine. Does that make sense? Could it fit?

**Comment by alexandru-calinoiu** [comment]
Ok, will double check my code, thank you.
