### ISSUE TITLE
DB Subnet Group id for Cluster returns nil

### ISSUE THREAD

**Issue by chanakyad-cuelogic** [fog/fog-aws#292]
**irb(main):009:0> connection.clusters.get('cluster_id')**

> <Fog::AWS::RDS::Cluster
    id="cluster_id",
    allocated_storage=1,
    backup_retention_period=1,
    db_cluster_members=[{"DBInstanceIdentifier"=>"auroradbaa", "master"=>true}],
    db_cluster_parameter_group="default.aurora5.6",
    **db_subnet_group=ni**l,
    endpoint="auroradbaa............",
    engine="aurora",
    engine_version="5.6.10a",
    password=nil,
    master_username="username",
    port=3306,
    preferred_backup_window="10:51-11:21",
    preferred_maintenance_window="sat:11:31-sat:12:01",
    state="available",
    vpc_security_groups=[{"VpcSecurityGroupId"=>"sg_id"}]
  >

**irb(main):010:0> a.describe_db_clusters('cluster_id').body['DescribeDBClustersResult']['DBClusters'].first**

=> {
    "AvailabilityZones"=>[
        
    ],
    "VpcSecurityGroups"=>[
        {
            "VpcSecurityGroupId"=>"sg-aac12bc3"
        }
    ],
    "AllocatedStorage"=>"1",
    "PreferredBackupWindow"=>"10:51-11:21",
    "Endpoint"=>"auroradb22-cluster.cluster-c3lcn90no87a.ap-south-1.rds.amazonaws.com",
    "Engine"=>"aurora",
    "EngineVersion"=>"5.6.10a",
    "MasterUsername"=>"chanakya",
    "DBClusterMembers"=>[
        {
            "DBInstanceIdentifier"=>"auroradb22",
            "master"=>true
        }
    ],
    "Status"=>"available",
    "Port"=>"3306",
    "PreferredMaintenanceWindow"=>"sat:11:31-sat:12:01",
    "BackupRetentionPeriod"=>"1",
    "DBClusterParameterGroup"=>"default.aurora5.6",
    "DBClusterIdentifier"=>"auroradb22-cluster"
}

-  connection.cluster.get('cluster_id') 

> `db_subnet_group => nil`

- a.describe_db_clusters('cluster_id').body['DescribeDBClustersResult']['DBClusters'].first
- 'SubnetGroupName' is not present at response

**Comment by geemus** [comment]
There is probably an error/omission in the parser for this, which may need updated to accommodate this particular bit. Would you be interested in helping us to improve this? Usually for something like this the best approach is to comment-out the parser line in the request method and run it (which should give you back the raw XML), then you can compare against the parser and see what might be unexpected and adjust it to accommodate. Thanks!

**Comment by chanakyacool** [comment]
@geemus 
please look at the fix for the above issue 
https://github.com/fog/fog-aws/pull/293
