### ISSUE TITLE
Cross account access using IAM role

### ISSUE THREAD

**Issue by maheshb-cuelogic** [fog/fog-aws#294]
Hi there,
 I am trying to access resources with an IAM role. This IAM role has access to multiple account.
Can anyone guide me how to access or create connection using IAM role for different accounts.

Thanks

**Comment by jkburges** [comment]
I'm not sure if this is what you mean, but if the EC2 instance on which your code is running has an instance role, and you want to use fog to interact with AWS, you could do something like the following:

```
require "aws-sdk"

# Get a temporary token from STS
token = Aws::STS::Client.new.get_session_token

compute = Fog::Compute.new(:provider => 'AWS', :aws_access_key_id => token.credentials.access_key_id, :aws_secret_access_key => token.credentials.secret_access_key)
```
