### ISSUE TITLE
Fog directory appends local system path with amazon url when i try to give dynamic fog directory

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#295]
I am using FOG with Paperclip. I added the following code to give dynamic directory name.

fog_directory: proc { |file| file.instance.repo.name }

It creates the fog directory correctly but when i try to get url it added the local system path with amazon url.

https://s3.amazonaws.com/%23%3CProc:0x4ae8f3bb@/home/apple/projects/project.name/config/initializers/paperclip.rb:8%3E/abc.jpg

Original issue opened at fog/fog#3874 by @vf-sohail

**Comment by plribeiro3000** [comment]
cc/ @geemus

**Comment by geemus** [comment]
I don't think it is expected to be a proc, so the outputted value there is probably the result of `to_s` on the proc as called by `"#{fog_directory}` when building the value. You may be able to work around this by making a class that responds to to_s and returns the custom value though.
