### ISSUE TITLE
Fog transfer acceleration endpoints

### ISSUE THREAD

**Issue by ilyakatz** [fog/fog-aws#303]
When using `Fog::Storage` with `AWS`

Method `put_object_url` does not support [AWS Transfer Acceleration](https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/).

Usually, you can you can upload files to `https://s3.amazonaws.com/bucketname`, however, with transfer acceleration, it needs to be `https://bucketname.s3-accelerate.amazonaws.com`, hence the parameter [`bucket_name`](https://github.com/fog/fog/blob/master/lib/fog/internet_archive/requests/storage/put_object_url.rb#L18) becomes superfluous

**Comment by geemus** [comment]
I'd be happy to support a pull request around this, but I'm afraid I don't have bandwidth to do it myself in the near future. Would you be interested in working on this with us? Thanks!

**Comment by ilyakatz** [comment]
Sure, I can give it a shot. It seemed to me that `bucket_name` is a fundamental part of `fog` so I can't just remove it as required parameter? If you point me in the right direction, I'd be happy to create a PR

**Comment by geemus** [comment]
I don't think you should need to change the bucket name portion, though I could be wrong. I think it should default to the subdomain version in most cases. It may just be a matter of allowing a special region/endpoint for accelerate in particular (similar to how you can use other regions). At a guess anyway, that seems nearer to the right track. Does that help and make sense?

**Comment by ilyakatz** [comment]
When using acceleration, you don't need the bucketname after the hostname. eg

```
https://bucketname.s3-accelerate.amazonaws.com/folder/file
```

However, with `fog` using `host` key in the parameters it will look something like this

```ruby
storage = Fog::Storage.new({
            host:"bucketname.s3-accelerate.amazonaws.com",
          }.merge(credentials)
        )
storage.put_object_url(
          "bucketname", #since this is required
          obj_name
        )
```

And the result will be 

```
https://bucketname.s3-accelerate.amazonaws.com/bucketname/folder/file
```

**Comment by geemus** [comment]
Hmm. Maybe we should just consider adding something like `put_accelerated_object_url`? Otherwise we could probably add options, but a new method might be somewhat cleaner/easier (implementation-wise anyway). What do you think?

**Comment by ilyakatz** [comment]
That makes sense. I can write up a PR.

**Comment by geemus** [comment]
Sounds good, thanks!

**Comment by jsantos** [comment]
@ilyakatz's solution worked for me while using V2 signatures... If I just leave it as default (V4), I get a `Bad Request` response. Has this happened to anyone?

**Comment by ilyakatz** [comment]
@jsantos oh, i didn't realize that they had different versions for signatures. is there an easy way to reproduce it?

**Comment by jsantos** [comment]
Well, my codebase was using `aws_signature_version:  '2'` since some time ago, because I had a module that could either use S3 and RiakCS (the latter only supports this version).

But if no `aws_signature_version` is specified, it defaults to 4. 

According to what I see [here](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/signaturev4.rb#L68), the region is part of the signing process, and in my case I'm not able to do any requests if I don't specify any signature version and the region is set to `accelerate`.

If I change the region to something like `us-east-1`, everything works fine.

**Comment by ilyakatz** [comment]
hm, honestly, i'm not sure how to go about this. should i make a note that it's only compatible with v4?

**Comment by IAPark** [comment]
For anyone else who might run into this. I think you can sidestep the issue by adding this to the options hash
``` ruby
{host: "s3-accelerate.amazonaws.com", path_style: false}
```
