### ISSUE TITLE
Is there a configuration setting for the AWS provider to adjust the url scheme for S3 buckets?

### ISSUE THREAD

**Issue by stevenmaguire** [fog/fog-aws#305]
There is a [closed issue](https://github.com/fog/fog/issues/3318) related to accessing buckets with virtual host over HTTPS. In my experience accessing the bucket using the alternate naming scheme works well over https. Is there an existing config to use the alternate URL pattern?

`https://my.production.bucket.s3.amazonaws.com/myObject` has problems

`https://s3.amazonaws.com/my.production.bucket/myObject` works

Any thoughts?

**Comment by geemus** [comment]
I believe the option you would want would be `:path_style => true` on the connection? Let me know if that is insufficient though. Thanks!

**Comment by stevenmaguire** [comment]
Perfect. That's exactly what I was looking for. Is that setting documented anywhere? I attempted to look! I'm usually a very RTFM kind of person...

**Comment by geemus** [comment]
I think it's in comments in the code, but maybe not much more than that. Would certainly welcome help making it clearer. Thanks!
