### ISSUE TITLE
autoscaling create launch config doesn't work with BlockDeviceMappings 

### ISSUE THREAD

**Issue by benmullin333** [fog/fog-aws#307]
Seems like this line should be `AWS.indexed_param` maybe?  
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/auto_scaling/create_launch_configuration.rb#L60

**Comment by geemus** [comment]
Sounds possible. Was there more to discuss here? Thanks!

**Comment by benmullin333** [comment]
No, apologies, this was my mistake.

**Comment by geemus** [comment]
No worries, thanks for clarifying.
