### ISSUE TITLE
Support new Ohio region (us-east-2)

### ISSUE THREAD

**Issue by mark-greene** [fog/fog-aws#313]
I get the following when I try to access the Ohio region:

`.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fog-aws-0.12.0/lib/fog/aws.rb:234:in validate_region!': Unknown region: "us-east-2" (ArgumentError)
`

**Comment by geemus** [comment]
Yeah, we have that in place to try and make it more nice and explicit if an invalid region gets passed in (unfortunately it means we need to add new regions as they appear). I think it just needs to be in this list if you'd like to help us update: https://github.com/fog/fog-aws/blob/master/lib/fog/aws.rb#L228 (you could also monkey-patch this method if you need it immediately). Thanks!

**Comment by mark-greene** [comment]
Monkey-patching gets past the first issue easily but the real problem is `change_resource_record_sets.rb'.  I can't find the magic IDs for `elb_hosted_zone_mapping` and `elb_dualstack_hosted_zone_mapping`.  Hovering in the console no longer works (at least for me).

**Comment by geemus** [comment]
Ah, yeah that is problematic. Looks like it might be available via list hosted zones? http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListHostedZones.html

**Comment by chanakyacool** [comment]
@mark-greene and @geemus 
+ added new region 'us-east-2' ohio support  
please check https://github.com/fog/fog-aws/pull/314

**Comment by mark-greene** [comment]
I'll check it out.  I found the IDs (http://docs.aws.amazon.com/general/latest/gr/rande.html#elb_region) for ELBs.  DNS works well for Instances and ELBs in any region other than Ohio.  I haven't been able to successfully monkey-patch `elb_dualstack_hosted_zone_mapping` (not something I do very often).  Still getting error:


.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:7:in `response_call': InvalidChangeBatch => &quot;&quot; is not a valid hosted zone id. is not a valid encrypted identifier (Fog::DNS::AWS::Error)

**Comment by geemus** [comment]
@mark-greene got it. If you share the monkey-patch attempt code I might be able to figure out what is going awry.

**Comment by mark-greene** [comment]
Just tried the simple patch of `elb_dualstack_hosted_zone_mapping`

```
module Fog::DNS
  class AWS
    # See https://forums.aws.amazon.com/message.jspa?messageID=612414
    def self.elb_dualstack_hosted_zone_mapping
      @elb_dualstack_hosted_zone_mapping ||= {
        "ap-northeast-1" => "Z14GRHDCWA56QT",
        "ap-southeast-1" => "Z1LMS91P8CMLE5",
        "ap-southeast-2" => "Z1GM3OXH4ZPM65",
        "eu-central-1"   => "Z215JYRZR1TBD5",
        "eu-west-1"      => "Z32O12XQLNTSW2",
        "sa-east-1"      => "Z2P70J7HTTTPLU",
        "us-east-1"      => "Z35SXDOTRQ7X7K",
        "us-east-2"      => "Z3AADJGX6KTTL2",
        "us-west-1"      => "Z368ELLRRE2KJ0",
        "us-west-2"      => "Z1H1FL5HABSF5",
      }
    end
  end
end

```

And I use it:

```
dns = Fog::DNS[:aws]
    zone = dns.zones.detect{|x| x.domain == zone }
    entry = zone.records.new name: record, type: 'A'
    entry.alias_target = {
      "DNSName": balancer.dns_name
    }
    entry.save

```

Doesn't work in Ohio unless I add `"HostedZoneId": "Z3AADJGX6KTTL2"`

**Comment by geemus** [comment]
Are you sure the entry you are working on is dualstack? Otherwise there is a second set of ids in that file here: https://github.com/fog/fog-aws/blob/09a405cc1474636f436406fc31c7b8baebaead8f/lib/fog/aws/requests/dns/change_resource_record_sets.rb#L17 (which you might have to patch as well/instead).

**Comment by mark-greene** [comment]
Yes, It's dualstack and I've tried both.  I haven't spent any more time trying to figure out the patch and am just living with the alias_target workaround.  When I get the chance (If it's not been addressed) I try to figure out the patch.

**Comment by geemus** [comment]
Sounds good, thanks for the update.

**Comment by chanakyad-cuelogic** [comment]
I think this PR has the required changes , if we can close this 
#332 

@geemus and @mark-greene

**Comment by geemus** [comment]
@chanakyad-cuelogic good catch, I believe you are correct.
