### ISSUE TITLE
Add creation_date field for aws images

### ISSUE THREAD

**Issue by puneetloya** [fog/fog-aws#320]
http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Image.html#creation_date-instance_method

The AWS SDK does give us this field. It is useful in cases where we need to clean up images created on a older date and there are other cases too.

Let me know if there is a solution to this. I was using describe_images method and I don't see the field.

I can work on it, if this not already done.

**Comment by lanej** [comment]
@puneetloya looks like it is not done.  We would gladly accept a PR with this addition. 

For Reference:
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Image.html
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html
* https://github.com/fog/fog-aws/blob/7e5e6ff/lib/fog/aws/parsers/compute/describe_images.rb
