### ISSUE TITLE
Fog::Compute::AWS::Image not properly loaded

### ISSUE THREAD

**Issue by tisba** [fog/fog-aws#324]
Using fog-aws 0.12.0 on ruby 2.3.1p112

I was trying to test that my code works properly when receiving a `Fog::Compute::AWS::Image`. As I'm using RSpec I was trying this:

```ruby
instance_double(Fog::Compute::AWS::Image)
```

This triggers a `NameError: uninitialized constant Fog::Compute::AWS::Image` though, even though fog is required and used.

I could only get it working in my specs reliabaly by explicitly requiring `fog/aws/models/compute/image`.

In non-test code this works fine, but only because we use other APIs to fetch a list of images (it seems in those cases the class is properly loaded).

Is this a bug? If not, what is the recommended best practice in those cases?

**Comment by lanej** [comment]
@tisba related classes are loaded after client instantiation.`Fog::Compute::AWS.new` will cause models, collections, and requests to be required.

See:
* https://github.com/fog/fog-core/blob/f6ef6c3d9458bc235be57100acdced264e85e52a/lib/fog/core/service.rb#L100
* https://github.com/fog/fog-aws/blob/13fb36d/lib/fog/aws/compute.rb#L18

**Comment by tisba** [comment]
So the recommendation would be to set up the test/example by calling `Fog::Compute::AWS.new`?

Thanks, that works for me. It's not perfect, but better then requiring the file directly :)

**Comment by lanej** [comment]
@tisba instantiating a client is the safest solution.  Depending on your usage, requiring the individual file may be sufficient.
