### ISSUE TITLE
Support for AWS Application Load Balancer (ALB)

### ISSUE THREAD

**Issue by daugustus** [fog/fog-aws#335]
I am unable to find any details about using Fog with the new Application Load Balancers that AWS. Any news on this?

https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

Thanks,
Dave

**Comment by geemus** [comment]
Things are generally added as somebody has a need (or just desire) to use them. I haven't heard any other discussion, so you may be the first one to raise it so far. Would you be interested in helping us work toward that? Thanks!

**Comment by daugustus** [comment]
That was a thought I had as well. I will take a look and see what is involved.

**Comment by geemus** [comment]
Sounds good, just let us know if there is anything we can assist with.

**Comment by daugustus** [comment]
To get started on this, do you have any pointers or guides for this project? or for Ruby in general?

**Comment by geemus** [comment]
There is a high level overview here: https://github.com/fog/fog/blob/master/CONTRIBUTING.md as well as http://fog.io/about/structure.html. If you are familiar with one or more of the existing aws services, a lot should be pretty similar too. As for Ruby, there are many good resources online, but I'm a bit of an old hand at this point so I'm not sure I have good recommendations for someone more new to it. Hope that helps!

**Comment by rockhunters08** [comment]
Has anyone started to work on this?  I could use it, so would do so if not.

**Comment by lanej** [comment]
@rockhunters08 afaik no one has started this and we'd be happy to receive a PR adding support for it.

**Comment by rockhunters08** [comment]
@lanej Ok, I'll start taking a look at it next week. Thanks.

**Comment by tomazstrukeljdlabs** [comment]
Does method target_health_descriptions work yet?
- target_health_descriptions returns "(Object doesn't support #inspect)"
- target_health_descriptions.get(ARN) returns "NoMethodError: undefined method `id' for nil:NilClass"
