### ISSUE TITLE
How to use iam_instance_profile?

### ISSUE THREAD

**Issue by tisba** [fog/fog-aws#342]
I'm a bit confused on how to set the IAM Role when launching EC2 instances.

I assume that `iam_instance_profile` is what I need to use, but regardless of what I pass to `create` it seems to be ignored. When I ask the returning instance `Fog::Compute::AWS::Server#iam_instance_profile` I get returned an empty Hash.

My question would be: What am I supposed to provide here? The ARN (as a String), like  `"arn:aws:iam::000000000000:instance-profile/some-name"`? In case it has the be a Hash, like the reader suggests, what needs to be passed?

## Update

I stumbled across https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/server.rb#L151-L152, but I just cannot figure out what to pass to `create` so that these instance variables get assigned.

**Comment by geemus** [comment]
@tisba sorry this seems to have gotten lost in the shuffle (a long time ago). Did you ever find what you needed?

**Comment by tisba** [comment]
hehe, thank you for asking. But no, not really 😀 Back then we found some workaround. Some time ago we moved to a pure AWS setup and migrated from fog to the official SDK.

Since I have your attention anyway: Thank you for fog, it was of great help to us for almost 2 years 🙇

**Comment by geemus** [comment]
Got it, makes sense. Glad it was helpful, at least for a time. If memory serves, fog predated the official SDK, so it seemed more necessary at the time (and the ability to do cross-cloud stuff can be nice, but practically speaking is not usually something people need/want). So I totally understand relying on the official SDK.
