### ISSUE TITLE
models/elb/model_tests does not properly cleanup

### ISSUE THREAD

**Issue by voxik** [fog/fog-aws#347]
This always fails:

```
$ FOG_MOCK=true shindo tests/models/elb/model_tests.rb tests/requests/efs/file_system_tests.rb

... snip ...

      #describe_mount_target_security_groups(fsmt-ahaykiuc) - has proper format
      undefined method `group_id' for nil:NilClass (NoMethodError)
        /builddir/build/BUILD/fog-aws-1.2.0/usr/share/gems/gems/fog-aws-1.2.0/tests/requests/efs/file_system_tests.rb:87:in `block (3 levels) in <top (required)>'
        tests/helpers/formats_helper.rb:92:in `block in formats'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:116:in `test'
        tests/helpers/formats_helper.rb:85:in `formats'
        /builddir/build/BUILD/fog-aws-1.2.0/usr/share/gems/gems/fog-aws-1.2.0/tests/requests/efs/file_system_tests.rb:85:in `block (2 levels) in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /builddir/build/BUILD/fog-aws-1.2.0/usr/share/gems/gems/fog-aws-1.2.0/tests/requests/efs/file_system_tests.rb:6:in `block in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        /builddir/build/BUILD/fog-aws-1.2.0/usr/share/gems/gems/fog-aws-1.2.0/tests/requests/efs/file_system_tests.rb:1:in `<top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
```

This seems to be due to [[1]], precisely due to [[2]] and [[3]]. These calls are messing up with the Fog::Compute[:aws].security_groups, where the failing test above probably expects the security_groups to be empty and therefore the default fallback [[4]] should be used.

[1]: https://github.com/fog/fog-aws/blame/master/lib/fog/aws/requests/elb/create_load_balancer.rb#L59
[2]: https://github.com/fog/fog-aws/blame/master/lib/fog/aws/requests/elb/create_load_balancer.rb#L125
[3]: https://github.com/fog/fog-aws/blame/master/lib/fog/aws/requests/elb/create_load_balancer.rb#L147
[4]: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/compute.rb#L193

**Comment by geemus** [comment]
@voxik thanks for the detailed report.

@lanej do you have thoughts/context on this? Thanks!

**Comment by lanej** [comment]
@voxik @geemus #348 has the fix.

**Comment by voxik** [comment]
@lanej I don't think the patch is changing anything ... actually, looking at the travis results, it triggers precisely the issue I am complaining about. You leave behind the newly created security groups. You should clean them up.

**Comment by voxik** [comment]
Of course the cleanup could be done in the failing tests, but that is just workaround IMO.

**Comment by lanej** [comment]
Correct. It was not as easy I initially thought.  The default security groups are created as a side-effect when creating a load balancer.  The EFS tests don't create a load balancer and therefore don't have access to them.  

It works on CI because the ELB tests run BEFORE the EFS tests.
