### ISSUE TITLE
Creating instances in AWS fails with Socket Error

### ISSUE THREAD

**Issue by phanindrakalva** [fog/fog-aws#352]
We are seeing below error when ever we try to create instances in AWS. Sometime it succeeds but most of the time it is throwing error. If we try to create 5 nodes it creates, 1 or 2 and fails on other.

> ```
> Failure/Error: conn.servers.length
> Excon::Error::Socket:
> XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)

> ```

```

      Fog::Compute.new(
        :provider               => 'AWS',
        :region                 => @region,
         :use_iam_profile              => true
      )
 def valid_connection?(conn)
     conn.servers.length
     true
   rescue Excon::Errors::Forbidden, Excon::Errors::Unauthorized, Fog::Compute::AWS::Error
     false
   end
```

This is how I call create_instance method

```

servers = aws.create_servers!(
      conn,
      nodes,
      {
        os_type: ENV['OS_TYPE'],
        key: ENV['KEY_NAME'],
        security_group_ids: [ENV['SECURITY_GROUP_ID']],
        subnet_id: ENV['SUBNET_ID'],
        num_of_vols: 2,
        vol_size: 250,
        flavor_id: ENV['FLAVOR_ID'],
        instance_tag: cluster_name,
        availability_zone: 'us-west-2a'
      }
    )

def create_server!(conn, instance_tag, opts = {})
  options = {
      :key => 'test',
      :security_group_ids => %w(sg-xxxxxx),
      :flavor_id => 'm4.2xlarge',
      :os_type => 'ubuntu',
      :num_of_vols => 2,
      :vol_size => 200,
      :root_vol_size => 50,
      :vol_type => 'ebs',
      :iops => 0
  }.merge(opts)

  unless valid_connection?(conn)
    @log.error 'Unable to authenticate with AWS, check your credentials'
    exit 2
  end

  case options[:os_type].downcase
  when 'ubuntu'
    server = create_server(
      conn,
      options[:key],
      instance_tag,
      options[:security_group_ids],
      options[:flavor_id],
      @ubuntu_amis[@region],
      options[:subnet_id],
      options[:private_dns_name],
      :num_of_vols => options[:num_of_vols],
      :vol_size => options[:vol_size],
      :root_ebs_size => options[:root_vol_size],
      :vol_type => options[:vol_type],
      :iops => options[:iops]
    )
    return server
  else
    @log.error 'Provided OS not supported yet!'
    exit 2
  end
end
```

I tried to enable the debug logging as well but it does not show much info.

**Comment by geemus** [comment]
Strange, I'd guess something wrong in the generation of the XML due to one or more of the parameters passed. But if that were the case I would expect a more consistent failure, is it possible that particular values for those parameters are always failing, while others succeed? If we could pin down more specifically what is going wrong it would make it much easier to fix.

See also: http://stackoverflow.com/questions/42685183/fog-creating-instances-in-aws-fails

**Comment by phanindrakalva** [comment]
It always fails on valid_connection? function.

**Comment by geemus** [comment]
Strange, googling seems to indicate it is likely whitespace at the beginning of the document (or similar). I really am not sure how that would be introduced here though (and why it wouldn't be a more widespread issue). @lanej any ideas?

**Comment by phanindrakalva** [comment]
I found one issue in my code. When I'm calling a create server method I'm passing security_group_ids as array instead of string. Changing that to string reduced the error rate but still I see this error occasionally.    

However, it is strange that if I pass a wrong data type it should fail for all the servers but it is failing only on some nodes.

**Comment by geemus** [comment]
Yeah, that is strange. Is is possible that some of the security_group_ids values were singular? So that only when there was more than one did it cause a problem? Not certain about that one at all, but it's the only other thing I can think of as a variable at the moment.

**Comment by phanindrakalva** [comment]
I never used multiple security groups for creating the servers. I'm passing only one security group for all the servers.

**Comment by lanej** [comment]
@geemus I have seen a similar error before but I don't have any clues to what is causing this one.
