### ISSUE TITLE
Do we need to list all files before creating one?

### ISSUE THREAD

**Issue by fidalgo** [fog/fog-aws#357]
By looking at the docs and the source:
```
 def files
  @files ||= Fog::Storage::AWS::Files.new(:directory => self, :service => service)
end
```
Do we really need to list all the files? I know we are memoizing them, but that will fail if it runs on a scheduled task and if you have like millions of files it would take a lot more time and memory than if we have an option to just put the file.

**Comment by geemus** [comment]
The actual file list should be lazy loaded. So just referring to files here gets you a local object that refers to the directory/file list, but hasn't yet fetched it. I think that should give you what you are after already, but do let me know if I misunderstand. Thanks!
