### ISSUE TITLE
Tag instances upon creation of new instance

### ISSUE THREAD

**Issue by ldanielw1** [fog/fog-aws#359]
I don't see much documentation on how to create a new instance with assigned tags (per https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/). Was wondering if this functionality already exists, and if not, if it would be possible to add it?

**Comment by geemus** [comment]
If you are using the model interface, you can pass an array of tags to the initializer and when save is called, the tags should be created (you can find related code here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/volume.rb#L69). Hope that solves this for you, but let me know if you have further questions. Thanks!

**Comment by ldanielw1** [comment]
Sorry, this doesn't quite answer my question. I want a single command that will create an instance AND tag it at the same time. Is run_instances able to do this, if I pass a key-value pair to the input hash?

**Comment by geemus** [comment]
Ah, I see. No, it does not appear that we currently support this, though it could be added.

Our current implementation of `RunInstances` (https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/compute/run_instances.rb) hasn't been updated to add/pass the new params, but it could be. Details can be found here (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html), under TagSpecification.

Would you be interested in working on this to help us update to enable it? Thanks!

**Comment by ldanielw1** [comment]
Hm - I'm afraid I'm really strapped for time atm, and not even well acquainted with the codebase here. Perhaps somebody else can take this task?

**Comment by geemus** [comment]
@ldanielw1 no worries, thanks for being up front about it. I'm in a similar place, but will keep an eye out for helpers. Thanks!

**Comment by ldanielw1** [comment]
Sounds good - thanks! Would it be possible to keep this ticket open in the meantime then, for people to volunteer...?

**Comment by geemus** [comment]
@ldanielw1 yeah, sure thing.

**Comment by jhoblitt** [comment]
I found this issue by searching the repo for `TagSpecification`.  Any chance this ticket could be reopened?

**Comment by geemus** [comment]
@jhoblitt sure, I didn't realize we had closed it. I'm happy to support someone implementing this, but probably don't have bandwidth to implement and test it myself.
