### ISSUE TITLE
The action `ModifyVolume` is not valid for this web service.

### ISSUE THREAD

**Issue by maheshb-cuelogic** [fog/fog-aws#363]
I am using `modify_volume` method to update `volume`. But when I hit the method it throws an error `Fog::Compute::AWS::Error: InvalidAction => The action ModifyVolume is not valid for this web service.`.

> irb(main):006:0> connection.modify_volume('volumeId', {'Size'=> 9})

    Fog::Compute::AWS::Error: InvalidAction => The action ModifyVolume is not valid for this web service.
    
    from /home/.gem/ruby/2.1.0/gems/excon-0.55.0/lib/excon/middlewares/expects.rb:7:in `response_call'
    
    from /home/.gem/ruby/2.1.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
    
    from /home/.gem/ruby/2.1.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
    
    from /home/.gem/ruby/2.1.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
    
    from /home/.gem/ruby/2.1.0/gems/fog-xml-0.1.3/lib/fog/xml/sax_parser_connection.rb:35:in `request'
    
    from /home/.gem/ruby/2.1.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:7:in `request'
    
    from /api/lib/fog/aws/compute.rb:528:in `_request'
    
    from /api/lib/fog/aws/compute.rb:523:in `request'

Doing through CLI(works fine):
   >   $ aws ec2 modify-volume --region ap-south-1 --volume-id vol-xxxxxxxxxxxxxxxx --size 5 

    {
        "VolumeModification": {
            "TargetSize": 5, 
            "TargetVolumeType": "gp2", 
            "ModificationState": "modifying", 
            "VolumeId": "vol-xxxxxxxxxxxxxxxx", 
            "TargetIops": 100, 
            "StartTime": "2017-05-03T15:21:01.444Z", 
            "Progress": 0, 
            "OriginalVolumeType": "gp2", 
            "OriginalIops": 100, 
            "OriginalSize": 4
        }
    }

**Comment by geemus** [comment]
@ehowe I believe you added this, any insights into what might be going wrong?

**Comment by ehowe** [comment]
The required API version is 2016-11-15 which I did update at some point (seems that it was with a different commit than when I added this), but that is the error that you would get if you were using an old API version.  @maheshb-cuelogic are you explicitly passing in an API version by chance?

**Comment by geemus** [comment]
@ehowe ah, yeah that makes sense. Thanks for the update.

@maheshb-cuelogic you may want to ensure you have the latest `fog-aws` also, as it may be you have a version with the new method, but not the new API version (since they didn't occur at the same time).

**Comment by chanakyacool** [comment]
@ehowe , @geemus 
- I too believe that the `api_version` when triggered `modify_volume` could be older than 2016-11-15 , i;e it would be  2014-10-01
- if the version has been explicitly changed or `fog/aws/compute.rb` has different version than 2016-11-15 , please update the files to latest version and try again

**Comment by maheshb-cuelogic** [comment]
Thanks guys. It was version issue. I am closing it.

**Comment by geemus** [comment]
@maheshb-cuelogic thanks for the update, glad it's working for you.
