### ISSUE TITLE
Fog::AWS::IAM::Error: InvalidAction => Could not find operation "ReplaceIamInstanceProfileAssociation" for version 2010-05-08

### ISSUE THREAD

**Issue by sourabhu-cuelogic** [fog/fog-aws#368]
I am implementing 3 API which were recently added in AWS API.
 - [ReplaceIamInstanceProfileAssociation](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceIamInstanceProfileAssociation.html)
 - [AssociateIamInstanceProfile](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateIamInstanceProfile.html)
 - [DescribeIamInstanceProfileAssociations](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeIamInstanceProfileAssociations.html)

 When I have added new method through metaprogramming in IAM but when I called the method, it throughs error message

> irb(main):006:0> connection.replace_iam_instance_profile_association("xxxxxxxxxxxxxx", type)

    Fog::AWS::IAM::Error: InvalidAction => Could not find operation ReplaceIamInstanceProfileAssociation for version 2010-05-08
    

Please let me know if you need more information or I missed anything.

**Comment by geemus** [comment]
In addition to adding the methods, you'll probably need to override the version value that is passed to IAM to match a newer version (which includes these methods). Otherwise you get routed to the old version of the API, which does not include the new stuff. Hope that helps, but let me know if you have further questions or I can better explain. Thanks!

**Comment by sourabhu-cuelogic** [comment]
If I change the `version` in `lib/fog/aws/iam.rb`, then issue remain the same and other methods like `get_group` also throughs same error for that particular `version`.

**Comment by geemus** [comment]
What version are you changing it to?

**Comment by sourabhu-cuelogic** [comment]
`compute` ->`2016-11-15`(tried this as this is in compute file)
`iam` -> `2010-05-08`
and some but doesn't work.

**Comment by geemus** [comment]
@lanej do you have any ideas? I'm struggling to find the current version numbers in docs...

**Comment by sourabhu-cuelogic** [comment]
@geemus - It has been resolved there was some library issues. It has been fixed. But got other error, here :

    connection.replace_iam_instance_profile_association('iip-assoc-xxxxxxxxxxxxxxxxx', {"arn" => "arn:aws:iam::xxxxxxxxxxxx:instance-profile/NAME", "name" => "NAME"})

    excon.error.response
    :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InternalError</Code><Message>An internal error has occurred</Message></Error></Errors><RequestID>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</RequestID></Response>"
    :cookies       => [
    ]
    :headers       => {
      "Connection" => "close"
      "Date"       => "Thu, 01 Jun 2017 07:24:21 GMT"
      "Server"     => "AmazonEC2"
    }
    :host          => "xxx.xx-xxxxx-x.amazonaws.com"
    :local_address => "xxx.xxx.xxx.xxx"
    :local_port    => xxxxx
    :path          => "/"
    :port          => 443
    :reason_phrase => "Internal Server Error"
    :remote_ip     => "xx.xx.xx.xx"
    :status        => 500
    :status_line   => "HTTP/1.1 500 Internal Server Error\r\n"

**Comment by geemus** [comment]
@sourabhu-cuelogic thanks for the update. A 500 is certainly harder to debug, I would double check that the request format is as-expected, but otherwise you may need to contact AWS support for further assistance.

**Comment by lanej** [comment]
I would recommend trying this call [via the official client](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#replace_iam_instance_profile_association-instance_method) and see if the exception is repeatable.
