### ISSUE TITLE
Support S3 object tagging

### ISSUE THREAD

**Issue by toupeira** [fog/fog-aws#377]
See http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

Looking at the code it looks like only bucket tags are implemented. Adding full support for object tags would involve at least the following:

- supporting the `x-amz-tagging` request header on [PUT Object](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)
- supporting the `x-amz-tagging-count` response header on [GET Object](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html)
- supporting the [GET Object tagging](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGETtagging.html), [PUT Object tagging](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTtagging.html) and [DELETE Object tagging](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETEtagging.html) methods

**Comment by geemus** [comment]
Sounds good, would you have availability to help us with a PR toward this? Thanks!

**Comment by toupeira** [comment]
@geemus unfortunately no, for our use-case we ended up using directories for grouping.

**Comment by geemus** [comment]
@toupeira ah, fair enough. Should that change in the future I would certainly welcome the help. In the mean time it will probably wait for somebody with a strong enough need/desire mix to work through it. Thanks for the update.
