### ISSUE TITLE
 Fog::Compute::AWS::Image#deregister ignores non-root snapshots.

### ISSUE THREAD

**Issue by eddiej** [fog/fog-aws#380]
The deregister method of Fog::Compute::AWS::Image accepts a `delete_snapshot` argument for cleaning up snapshots after deregistering an AMI (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/deregister-ami.html#clean-up-ebs-ami). If an AMI has more than one volume, only the root volume snapshot is deleted - 'orphan' snapshots for the other AMI volumes are left untouched. I'm not sure if this is intentional or not - is there a use case for leaving an AMI snapshot behind?

```
def deregister(delete_snapshot = false)
  connection.deregister_image(id)

  if(delete_snapshot && root_device_type == "ebs")
    block_device = block_device_mapping.detect {|block_device| block_device['deviceName'] == root_device_name}
    @connection.snapshots.new(:id => block_device['snapshotId']).destroy
  else
    true
  end
end
```

**Comment by geemus** [comment]
I'm really not sure. @lanej do you have context to share? Thanks!
