### ISSUE TITLE
Missing file for extraction?

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#390]
There is one file at [`fog`](https://github.com/fog/fog/blob/master/lib/fog/aws/service_mapper.rb) that is related to `aws`. Should we move it here or is it only related to the `fog` context?

**Comment by lanej** [comment]
@geemus would know but I think it should probably come over.  We shouldn't force the provider gems to change `fog` everytime a new service is expressed.

**Comment by geemus** [comment]
Moving it probably makes sense, as long as it doesn't break anything (which hopefully should be the case).
