### ISSUE TITLE
Cannot copy an encrypted snapshot from one account to another account

### ISSUE THREAD

**Issue by JudgeGregg** [fog/fog-aws#398]
Ruby 2.3.0
Fog 1.38.0
Fog aws 1.4.1

I have an encrypted snapshot belonging to account B.
That snapshot is tagged to allow access from account A.
```
require 'fog'

backup_options = {
   :provider => "AWS",
   :aws_access_key_id => 'AXXXXXXXXXXXXXX',
   :aws_secret_access_key => 'XXXXXXXXXXXXXXXXXX',
   :region => 'eu-central-1',
}

ec2_backup = Fog::Compute.new(backup_options)
snap_back = ec2_backup.copy_snapshot('snap-0xxxx', 'eu-central-1', 'RUBY')
``` 
fails with:
-snap-0xxxx
-0 Gio size
-RUBY desc
-error status
-0% progress
-not encrypted

whereas:
```
import boto3

ec2_resource = boto3.resource(
    'ec2',
    aws_access_key_id='AXXXXXXXXXXXXXXXX',
    aws_secret_access_key='XXXXXXXXXXXXXXXX',
    region_name='eu-central-1'
)

snap = ec2_resource.Snapshot('snap-0xxxx')
snap.copy(
    Description='PYTHON',
    SourceRegion='eu-central-1')
```
works fine:

-snap-0yyyyy
-8 Gio size
-PYTHON desc
-completed status
-100% progress
-encrypted

The keys are identical in both cases, and belong to account A. 

Is there anything else I have to configure? The copy worked just fine when the snapshot was not encrypted.

Thank you for your work on fog!

**Comment by geemus** [comment]
Afraid I don't have any recent experience with this. @lanej any chance you've had more exposure or have insights? Thanks!
