### ISSUE TITLE
Mocks for EC2 instance creation do not behave as expected

### ISSUE THREAD

**Issue by geofffranks** [fog/fog-aws#404]
When I create a server using the mocked AWS API in the below manner, I would expect the returned server object to have the following information (based on an experiment with the AWS live API today):

1. `security_group_ids` should have the IDs of the security groups associated with the VM (as should the `network_interface`'s `groupIds`).
2. `groups`, and the `network_interface`'s, `groupSet` attribute should have the names of the security groups associated with the VM
3. `vpc_id` on the server and `vpcId` on the `network_interfaces` should be set to the VPC id that is set on the subnet associated with the server / its network interfaces
4. `iam_instance_profile` should be set
5. The VM should not have a `public_ip_address`.

What I get:
1. `security_group_ids` is an empty array. The `groupIds` in the `network_interface` is nil.
2. `groups` is an empty array. The `groupSet` in the `network_interface` is nil.
3. `vpc_id` is nil, and `vpcId` on the `network_interface` is hard-coded to `mock-vpc-id`.
4. `iam_instance_profile` is an empty hash.
5. `public_ip_address` has a randomly generated public IP.

How I'm creating the VM:
```
        server = connection.servers.create(
          block_device_mapping: [{
            'DeviceName'     => '/dev/xvda',
            'Ebs.VolumeSize' => config[:opts][:disk_size_in_gb],
          }],
          key_name: config[:opts][:ssh_keypair_name],
          flavor_id: config[:opts][:instance_type],
          subnet_id: config[:opts][:subnet_id],
          image_id: image_id,
          private_ip_address: config[:ip],
          security_group_ids: security_group_ids,
          availability_zone: config[:opts][:availability_zone],
          iam_instance_profile_name: config[:opts][:instance_profile_name],
          tags: {
            'Name' => config[:name],
          }
        )
        server.wait_for { ready? }
```

**Comment by geemus** [comment]
@geofffranks Thanks for the detailed report. We've built up the mocks a little over time and done our best to keep them inline with current behavior, but sometimes some parts fall behind (and this seems likely to be the case here. Would you have capacity to help us work on bringing this up to date and adding these additional details? Thanks!
