### ISSUE TITLE
Clarify versioning on README

### ISSUE THREAD

**Issue by dLobatog** [fog/fog-aws#42]
It would be nice to know if this gem is going to follow semantic versioning like Fog, or other scheme. The reason why I ask is because I didn't know what kind of pinning should I use when including it in my gemspecs.

Thanks!

**Comment by geemus** [comment]
Definitely. I do my best with all stuff I work on to follow semantic, so I think it should be a pretty safe bet (though occasionally mistakes do get made). If you'd like to patch the README to indicate that, I'd certainly be happy to include the change.
