### ISSUE TITLE
could not create ec2 volume with custom encryption key, volume only create with default 'aws/ebs' encryption key

### ISSUE THREAD

**Issue by tusharm-cuelogic** [fog/fog-aws#420]

**Comment by geemus** [comment]
Could you share some additional detail of what sort of parameters you are passing when it does and doesn't work, as well as what error you are seeing? Thanks!

**Comment by tusharm-cuelogic** [comment]
I am using following command to create volume with custom key
aws ec2 create-volume --size 4 --region eu-west-1 --availability-zone eu-west-1a --volume-type gp2 --encrypted --kms-key-id arn:aws:kms:eu-west-1:{account_id}:key/8d291f25-63a2-4a29-86af-b3d427d34bd3

no error 
giving following response, but volume not is creating on aws
{
    "State": "creating",
    "KmsKeyId": "arn:aws:kms:eu-west-1:{acount_id}:key/8d291f25-63a2-4a29-86af-b3d427d34bd3",
    "VolumeId": "vol-080340885ce523c83",
    "Size": 4,
    "Encrypted": true,
    "VolumeType": "gp2",
    "Iops": 100,
    "AvailabilityZone": "eu-west-1a",
    "SnapshotId": "",
    "CreateTime": "2017-12-06T14:11:30.511Z"
}

**Comment by geemus** [comment]
Hmm. Are you sure that command uses fog-aws to execute? I suspect it might be aws-sdk?

**Comment by tusharm-cuelogic** [comment]
yes that command is for aws, i am sending same inputs value to fog-aws also, but volume is not getting creating.

**Comment by geemus** [comment]
That's strange, I would expect that if you got back a creating response it must be working. Is it possible that fog is using a different credential set (so that it wouldn't be visible from other sources)?
