### ISSUE TITLE
Option to turn off Warnings

### ISSUE THREAD

**Issue by amandapouget** [fog/fog-aws#426]
We get flooded by these warnings:
`[fog][WARNING] fog: the specified s3 bucket name(____) is not a valid dns name, which will negatively impact performance.`
Is there any way to turn these off or at least run quiet?

It's nuts to have one's terminal flooded with this until if / when changing our bucket names is really a priority.

**Comment by geemus** [comment]
I think you can do `Fog::Logger[:warning] = nil` to disable all warnings, I don't think there is presently a way to just mute this one message though. Does that help?

**Comment by mandysimon88** [comment]
Yes! This works. Thank you!

**Comment by geemus** [comment]
Closing as it seems like that was an acceptable answer.
