### ISSUE TITLE
Easily Delete S3 directory and it contents?

### ISSUE THREAD

**Issue by homerlex** [fog/fog-aws#435]
Is there an easy way to delete an S3 directory and all its contents?  I tried #delete_bucket but it only seems to work if there is nothing under the directory

**Comment by geemus** [comment]
I believe you would need to iterate over the objects and delete them, then the bucket. If you just need to do this once, it might be easier to use the CLI or web dashboard. Here are some related docs: https://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html

**Comment by homerlex** [comment]
Thanks for the reply.  I found a nice way to do it with the aws-sdk:

```
s3 = Aws::S3::Resource.new(region: S3_REGION)
bucket = s3.bucket(S3_BUCKET_NAME)
objects = bucket.objects({prefix: key})
objects.batch_delete!
```

I was hoping fog had something similar.

**Comment by geemus** [comment]
Fair enough, it's possible that I'm just forgetting or we hadn't yet implemented it too. In any event, I won't worry too much about it for the moment if you have a solution. Thanks for the update.
