### ISSUE TITLE
AWS Credentials required when using IAM Profile

### ISSUE THREAD

**Issue by fjahr** [fog/fog-aws#44]
Hi,

i am trying to access S3 from an EC2 Instance with Fog using only the IAM Profile but not the AWS Credentials (secret_key_id and secret_access_key are not available in the environment). However the credentials seem to be required even when using IAM. Should this not be possible? I expected that Fog would fetch the credentials for me when using IAM.

Thanks for your support!

**Comment by lanej** [comment]
you should get a set of keys when you generate your IAM profile.

**Comment by fjahr** [comment]
Could you hint me at documentation for that? All examples of the usage of Fog::AWS::IAM Modules start by being initialized WITH AWS credentials but I can't find an example for retrieving the temporary keys without having keys already.

Thanks a lot!

**Comment by geemus** [comment]
In my experience with IAM, you basically use it to give you other keys of equal or lesser privilege (which you then actually use for whatever operation you intend). That said, you generally need some keys to start down that path. I might be missing something in this particular case/context though.

**Comment by fcheung** [comment]
If you pass :use_iam_profile => true then fog should fetch credentials from the instance metadata for you

**Comment by fjahr** [comment]
Sorry for not responding anymore. I was assigned to a different project and can't look into the issue any further at the moment. I will try to get back to it when I have time. Thanks for your support anyway!

**Comment by geemus** [comment]
Thanks for the update!
