### ISSUE TITLE
AWS::ECS with `use_iam_profile` errors out

### ISSUE THREAD

**Issue by vovko** [fog/fog-aws#441]
When creating ECS client instance to use IAM profile via
```
client = Fog::AWS::ECS.new(use_iam_profile: true)
```
getting error:
```
2.4.1 :001 > require 'fog/aws'
 => true
2.4.1 :002 > Fog::AWS::VERSION
 => "2.0.1"
2.4.1 :003 > client = Fog::AWS::ECS.new( use_iam_profile: true )
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
```

when passing empty values for aws_access_key_id and aws_secret_access_key and trying to run a task:
```
client = Fog::AWS::ECS.new(use_iam_profile: true, aws_access_key_id: '', aws_secret_access_key:'')
client.run_task('cluster' => 'my-cluster', 'taskDefinition' => 'my-task')
```
getting:
```
Fog::AWS::ECS::Error: InvalidClientTokenId => The security token included in the request is invalid.
```

I was hoping CredentialFetcher would update my empty credentials via `use_iam_profile` but no luck
https://github.com/fog/fog-aws/blob/master/lib/fog/aws/ecs.rb#L59

Please let me know if I'm using it in a wrong way or there is a workaround.
Thank you in advance!

**Comment by geemus** [comment]
Hey, sorry to hear you are having trouble here. Unfortunately, I think there are a lot of variables.

I believe your first example above, passing just `use_iam_profile: true` should be correct. The fetched credentials get overwritten by any explicit values you pass, so I would expect that if you pass blank strings, that is what it will try to use. So just passing use profile should work if the context is correct (I think, or at least it USED to work).

Could you check through these bits from AWS to make sure it works outside fog as expected? https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_iam-ec2.html#troubleshoot_iam-ec2_no-keys

Thanks!

**Comment by fengshuo** [comment]
thanks for your reply @geemus .
I am wondering if it's possible to specify which profile to use in fog config? I have multiple profiles and I want to use one IAM profile, but there seems to be only the `use_iam_profile: true` option

**Comment by fengshuo** [comment]
thanks for your reply :)

**Comment by geofffranks** [comment]
We're running into this as well. With the latest fog-aws, if we build a VM using this:

```
      Fog::Compute.new({
        provider: "AWS",
        use_iam_profile: true,
        aws_access_key_id: "",
        aws_secret_access_key: "",
      })
```

We get the same error. However if we use this:

```
      Fog::Compute.new({
        provider: "AWS",
        use_iam_profile: true,
      })
```

the VM is able to build fine, *except* when we are testing - at that point the Fog mocks complain that we must specify those values:

```
     Failure/Error: aws.deploy_vm

     ArgumentError:
       Missing required arguments: aws_access_key_id, aws_secret_access_key
```

**Comment by geemus** [comment]
@geofffranks thanks for the details. I would expect the second one to be correct usage (despite some troubles around it in the past). The fact that the mocks complain is probably just an oversight, and I'd certainly welcome any help you might be able to give toward patching that to work as expected. Thanks!

**Comment by NgocNT-Ponos** [comment]
I've same issue

```
s3 = Fog::Storage.new(
  provider: 'AWS',
  use_iam_profile: true,
  aws_credentials_refresh_threshold_seconds: 60
)
[fog][WARNING] Unable to fetch credentials: EOFError (EOFError)
Traceback (most recent call last):
        1: from (irb):24
ArgumentError (Missing required arguments: aws_access_key_id, aws_secret_access_key)
Fog::AWS::VERSION
 => "3.28.0" 
```

**Comment by geemus** [comment]
@NgocNT-Ponos - Sorry to hear you are running into this. Were you ever able to get it working, or was it always broken? Also, could you try this to see if it is working outside of fog: https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_iam-ec2.html#troubleshoot_iam-ec2_no-keys
