### ISSUE TITLE
Release new version to RubyGems

### ISSUE THREAD

**Issue by NARKOZ** [fog/fog-aws#442]
Please release a new version of the gem with the updated dependencies - ec620d8e4b2af4ae5d61e23e66f9c6194003e258

**Comment by geemus** [comment]
@lanej not sure where we are on this. Could you advise (and/or cut a release if you are ready)? Thanks!

**Comment by lanej** [comment]
Requires #443

**Comment by lanej** [comment]
https://rubygems.org/gems/fog-aws/versions/3.0.0

**Comment by geemus** [comment]
Thanks!
