### ISSUE TITLE
How can I remove the `Content-Encoding` metadata properties if I upload from fog

### ISSUE THREAD

**Issue by phong-wildsky** [fog/fog-aws#447]
When I upload using fog-aws, the S3 file include the `Content-Encoding : Identity`.

I would like the CloudFront to compress the file to gzip for me. 
In order to do that we need to remove `Content-Encoding` from the S3 header ( ref : https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-custom-origin )

Therefore, is there any way not to include the `Content-Encoding` to the metadata when upload using fog-aws ??

Version : fog-aws 0.1.2

**Comment by geemus** [comment]
I don't think it should include anything by default, but I could be wrong. Could you share a code snippet of how you are using fog-aws currently to help me tailor advise? Thanks!

**Comment by geemus** [comment]
I believe that would modify the supplied encoding, but wouldn't add one if there wasn't already one there. I didn't see any obvious place where it set a default, but I could be overlooking something.
