### ISSUE TITLE
add region cn-northwest-1

### ISSUE THREAD

**Issue by x6j8x** [fog/fog-aws#455]
The second AWS region in China is open for some time now (6 months+). Please add.

**Comment by geemus** [comment]
Would you be up for making a pull request to help us add it? I'm happy to couch you through it if you have questions.

**Comment by x6j8x** [comment]
Sorry, I‘m not at all fluent in ruby. Actually l am just a user of a product using fog (cloudfoundry/cloud_controller_ng).

**Comment by geemus** [comment]
@x6j8x fair enough, I thought I would at least ask.

**Comment by geemus** [comment]
Added here: https://github.com/fog/fog-aws/commit/eb204b0396548dca072bff26bb74a71c017fab8a
