### ISSUE TITLE
Option to disable ssl verification

### ISSUE THREAD

**Issue by nifuki** [fog/fog-aws#465]
Hi,

I'm currently using fog-aws to upload backups to a self-hosted s3 compatible storage which uses self-signed certificates, so I need to disable peer SSL verification. As a workaround I add this before making a connection in `storage.rb`:
```
def _request(scheme, host, port, params, original_params, &block)
      Excon.defaults[:ssl_verify_peer] = false
      connection(scheme, host, port).request(params, &block)
```

If I'm not missing anything, now this is the only way to do it. This works for me, but it would be useful to add a configurable parameter to disable verification, especially for the development or local network environments.

How do you think, is it worth implementing this option?

Thanks!

**Comment by geemus** [comment]
I believe when you are setting up the connection you can pass a connection_options value which would include the ssl_verify_peer setting. So something like:

```
Fog::AWS::Storage.new(connection_options: { ssl_verify_peer: false }, ...)
```

Does that make sense? Reviewing the code, I'm pretty sure that should do what you need, but certainly let me know if you have further questions.

**Comment by nifuki** [comment]
Yes, it works, thanks for the clarification
