### ISSUE TITLE
head_url signed

### ISSUE THREAD

**Issue by mrloop** [fog/fog-aws#47]
I'm using presigned head requests, currently using [signed_url](https://github.com/fog/fog-aws/blob/b5c39ecd093da3917edea6ce7ab88f228649076d/lib/fog/aws/storage.rb#L140) but would like to use a new method on files **head_url** , similar to [get_url](https://github.com/fog/fog-aws/blob/b5c39ecd093da3917edea6ce7ab88f228649076d/lib/fog/aws/models/storage/files.rb#L80). Would a pull request with this be welcome?

**Comment by geemus** [comment]
Seems like a reasonable addition to me, thanks!

**Comment by mrloop** [comment]
See pull request https://github.com/fog/fog-aws/pull/51

**Comment by geemus** [comment]
Thanks!
