### ISSUE TITLE
Is DescribeImageAttribute support missing?

### ISSUE THREAD

**Issue by keithjpaulson** [fog/fog-aws#473]
There is a call to set launch permissions via modify_image_attribute, but I don't see a describe mechanism.

AWS docs at https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImageAttribute.html

**Comment by geemus** [comment]
Thanks for the heads up. It's not unlikely that we either overlooked this or it was added after we did other work. With things like this they usually get added when someone finds a need to use it. If you would like to work on adding it, I'd certainly be happy to support you in doing so. Thanks!

**Comment by keithjpaulson** [comment]
OK, I have code almost done.  Curiously, I'm getting Client.AuthFailure error looking up block dev mappings on AMIs that I created; AWS docs suggest this can happen (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImageAttribute.html)

I guess leave the support for block dev mapping in place, maybe it works for someone?

**Comment by keithjpaulson** [comment]
How does this look?
https://github.com/fog/fog-aws/pull/476

**Comment by geemus** [comment]
Looks good, thanks!
