### ISSUE TITLE
Mocks for VM creation require access and secret key when using instance profiles

### ISSUE THREAD

**Issue by teancom** [fog/fog-aws#482]
Currently, fog-aws allows/requires you to do this when using instance profiles:

```
Fog::Compute.new({
   provider: "AWS",
   use_iam_profile: true,
 })
```

Specifically, if you add an access and secret, the AWS api will complain. However, when mocking it, access_key_id and secret_access_key are required, even if they're set to an empty string:
```
Fog::Compute.new({
 provider: "AWS",
  use_iam_profile: true,
  aws_access_key_id: "",
  aws_secret_access_key: "",
})
```

**Comment by geemus** [comment]
@teancom Thanks for the detailed report. I think this is simply on oversight on our part that no one happened to bump into quite yet. We would certainly welcome help in patching this if you are able and willing. Thanks!

**Comment by teancom** [comment]
I'm willing but probably unable. I attempted to figure out what I would need to do to help out here, but frankly got very lost. I ended up opening https://github.com/fog/fog-aws/pull/485 just so that I could feel like I'd made *some* sort of contribution, but actually fixing this is apparently above my current skill level. Sorry. :-/

**Comment by geemus** [comment]
No worries. I'm happy to help answer any particular questions you might have, though it may be a bit difficult to fully outline from scratch how this might work. Thanks for the other tweaks and fixes, I appreciate it.
