### ISSUE TITLE
nil:NilClass error

### ISSUE THREAD

**Issue by sreeninair** [fog/fog-aws#483]
Hi Guys,

I am getting error while creating snapshots. Please help

```
volumes = conn.volumes.all().to_json

js = JSON.parse( volumes )

js.each { |k,v|
  key = k
  value = v
        volumesid = key['id']
        serverid = key['server_id']

         if serverid == "#{instanceid}"

# getting the instance name
instance = conn.servers.get("#{instanceid}")

snapshot = conn.snapshots.new

snapshot.description = "Autosnap instance name:  instance id:  #{serverid} of volume id:  #{volumesid}"
snapshot.volume_id = "#{volumesid}"

snapshot.save

conn.tags.create(:resource_id => snapshot.id, :key => "saas", :value => "snapshot", :key => "customername", :value => "#{instancename}" )
```

Thanks

```
snapshot.rb:84:in `block (3 levels) in <main>': undefined method `id' for nil:NilClass (NoMethodError)
    from snapshot.rb:52:in `each'
    from snapshot.rb:52:in `block (2 levels) in <main>'
    from /snapshot.rb:34:in `each'
    from  snapshot.rb:34:in `block in <main>'
    from snapshot.rb:12:in `each'
    from snapshot.rb:12:in `<main>'", 
```

**Comment by geemus** [comment]
It is a little hard for me to tell (because I can't correlate line numbers from the error message to the code). That being said, if the snapshot variable is nil, then all of the methods prior to id should fail also? I feel like I might be missing something though. Does that help at all? Could you help me understand a bit better the broader context?

**Comment by sreeninair** [comment]
Hi Geemus,

Here is the full code. Please help

#!/usr/bin/ruby
require 'fog'
require 'json'

AWSid = ARGV[0]
AWSkey = ARGV[1]

#Specify regions required

region = ["us-east-1", "eu-west-1", "ap-southeast-2"]
#region = ["ap-southeast-2"]
region.each { |x|



  ###


#aws api connection

conn = Fog::Compute::AWS.new(
{
 :aws_access_key_id => AWSid,
 :aws_secret_access_key => AWSkey,
 :region => x
}
)



servers = conn.servers.all().to_json
js = JSON.parse( servers )

js.each { |k,v|
  key = k
  value = v
        instanceid = key['id']
        instancepubip = key['public_ip_address']
        instancename = key['tags']['Name']

puts "#{instanceid}"


####################Creating snapshot

#listing volumes and taking it to json

volumes = conn.volumes.all().to_json

js = JSON.parse( volumes )

js.each { |k,v|
  key = k
  value = v
        volumesid = key['id']
        serverid = key['server_id']

         if serverid == "#{instanceid}"


# getting the instance name

   instance = conn.servers.get("#{instanceid}")



snapshot = conn.snapshots.new

snapshot.description = instance name:  instance id:  #{serverid} of volume id:  #{volumesid}"
snapshot.volume_id = "#{volumesid}"


snapshot.save

conn.tags.create(:resource_id => snapshot.id, :key => "test", :value => "snapshot", :key => "name", :value => "#{instancename}" )



snapid = conn.snapshots.get(snapshot.id)




snapname = snapid.id

puts "#{snapname} is created"


snapshot.reload



end
}

}


}


=====



snapshot.rb:84:in `block (3 levels) in <main>': undefined method `id' for nil:NilClass (NoMethodError)\n\tfrom snapshot.rb:52:in `each'\n\tfrom snapshot.rb:52:in `block (2 levels) in <main>'\n\tfrom /snapshot.rb:34:in `each'\n\tfrom  snapshot.rb:34:in `block in <main>'\n\tfrom snapshot.rb:12:in `each'\n\tfrom snapshot.rb:12:in `<main>'",

**Comment by geemus** [comment]
Hmm, if I'm seeing line numbers accurately, it looks like this must be successful:

```
conn.tags.create(:resource_id => snapshot.id, :key => "test", :value => "snapshot", :key => "name", :value => "#{instancename}" )
```

If that is the case, I think you could skip the `snapid = conn.snapshots.get(snapshot.id)` and just refer directly to the snapshot.id again. Get just returns nil if it doesn't find something, and it sounds like you may be running into an eventual consistency problem here. In particular, by creating and immediately querying you may be going faster than amazon is able to keep up (this is not uncommon). Using the value returned from the create should work. Alternatively, we sometimes will check for a nil in a case like this, pause, and retry 3-5 times (this is what `Fog.wait_for {}` is used for. These pauses/retries are usually enough to smooth out any delays on the amazon side.

Does that all make sense? Hopefully that gives you what you need here.
