### ISSUE TITLE
Access S3 using a proxy

### ISSUE THREAD

**Issue by stephanebruckert** [fog/fog-aws#486]
I need your help as I cannot see a proxy option in the gem.

I subscribed to a proxy service called QuotaGuard https://elements.heroku.com/addons/quotaguardstatic. My goal is to reach S3 using a static outbound IP address. 

> Route your outbound traffic through a load balanced pair of static IP addresses via our proxy. Allows you to integrate with third parties that require a known IP for whitelisting or open your own firewall to allow secure traffic through.

For a usage with Rails/Ruby, they suggest different alternatives (`rest-client`, `httparty`, `httpclient`): http://support.quotaguard.com/support/solutions/folders/5000048317. It should look like https://stackoverflow.com/a/37892151/1515819

I would like to achieve this but using fog-aws. `@client ||= Fog::Storage::AWS.new(...)`

I found a proxy option in https://github.com/fog/fog-core/blob/master/lib/fog/core/connection.rb#L42 `fog-core` but I saw that `fog-aws` does not use `fog-core`'s `Fog::Core::Connection` but `Fog::XML::Connection`, for which `proxy` is not detected. This has no effect:

    Fog::Storage.new({
       region: s3_region,
       provider: provider.upcase,
       aws_access_key_id: s3_access_key,
       aws_secret_access_key: s3_access_secret,
       connection_options: {
          proxy: (ENV["QUOTAGUARDSTATIC_URL"] if ENV["QUOTAGUARDSTATIC_URL"])
       }
    })

Do you have any idea how I could do that? Many thanks!

**Comment by stephanebruckert** [comment]
Okay I think I found what I wanted in `fog-core`! https://github.com/fog/fog-core/blob/master/lib/fog/core/connection.rb#L42

I will reopen in case of any issue. Thanks!

**Comment by stephanebruckert** [comment]
It doesn't seem that `fog-aws` is using `Fog::Core::Connection`?

**Comment by stephanebruckert** [comment]
Just saw that `fog-aws` does not use `fog-core`'s Fog::Core::Connection but `Fog::XML::Connection`, for which proxy is not detected.

This has no effect:

    Fog::Storage.new({
       region: s3_region,
       provider: provider.upcase,
       aws_access_key_id: s3_access_key,
       aws_secret_access_key: s3_access_secret,
       connection_options: {
          proxy: (ENV["QUOTAGUARDSTATIC_URL"] if ENV["QUOTAGUARDSTATIC_URL"])
       }
    })

Any help is very much appreciated.

**Comment by geemus** [comment]
Hmm. Well, I believe that fog-xml connection is a child class of the core connection, so I think that should fall back to the super class and still be used. It sounds like you are not getting the behavior you expect/desire from that though. If you set `EXCON_DEBUG=true` it may be helpful, as we should see what is actually being used. Could you try that and share the output? Thanks!

**Comment by stephanebruckert** [comment]
Thanks for the useful `EXCON_DEBUG=true` command! It helped me figure out that my environment wasn't properly configured (missing key + secret, but in reality I was uploading files locally and not on AWS... which is why I thought it was working).

The proxy works well, thanks for the great library!
