### ISSUE TITLE
ELBv2 Support ?

### ISSUE THREAD

**Issue by BentoumiTech** [fog/fog-aws#489]
I've been trying to get the list of available elb load balancers with FOG without success. 

I tried then with aws-cli running this command `aws elb describe-load-balancers` and I was getting an empty array too.

I saw that I needed to use elbv2 command `aws elbv2 describe-load-balancers` to retrieve the list of load balancers.

Does FOG support ELBv2 ?

**Comment by geemus** [comment]
Not yet (that I'm aware of). Are the commands not backwards compatible, or could we start updating to use them?

**Comment by Neophy7e** [comment]
I didn't tried all commands but the one that I tried with the CLI all worked the same. I would imagine it is but it would need more investigation.
