### ISSUE TITLE
With out AWS access key & secrect AWS services not working(IAM Role associated)

### ISSUE THREAD

**Issue by ranganathabrr** [fog/fog-aws#495]
It was working with out security credentials, I did composer update, and its updated new PHP SDK version. My AWS services stop working, If i provide security credentials its start working.

Ec2 instance associated with IAM Role, I don't want to expose security credentials.

**Comment by geemus** [comment]
This repository is for a Ruby library, so I'm not sure how PHP would impact it. Perhaps you need to ask in a different repository?
