### ISSUE TITLE
Warning: possibly useless use of == in void context

### ISSUE THREAD

**Issue by N0xFF** [fog/fog-aws#498]
`<compiled>: warning: possibly useless use of == in void context`

### How to reproduce:

```ruby
# Gemfile
...
gem "typhoeus"
gem "fog-aws"
...
```

For example run any blank test, enable warnings and disable spring:
```bash
DISABLE_SPRING=1 bin/rails test -w test/models/item_test.rb
```

**Comment by N0xFF** [comment]
I investigated where this warning comes from.

**fog-aws** uses **fog-core** which depends on **mime_types**.

**ruby_mime_types** delegates `==` via `Forwardable` module:
```ruby
  def_delegators :@container,
    :==,
    ...
```
https://github.com/mime-types/ruby-mime-types/blob/beed92cef1f304c967f53314f4668e787fd85128/lib/mime/types/container.rb#L50

Simple code to reproduce warning:
```ruby
# test.rb
require 'forwardable'

class Foo
  attr_accessor :bar
  extend Forwardable
  def_delegator :@bar, :==
end
```

```bash
> ruby -w test.rb
<compiled>: warning: possibly useless use of == in void context
```

In our production code we uses Ruby 2.4 and this warning is gone in 2.5.

**Comment by geemus** [comment]
Thanks for digging in and reporting back, hopefully it will not cause any problems beyond a warning for you and it's good to know it is no longer a problem with 2.5.
