### ISSUE TITLE
file.save does not work with STDIN

### ISSUE THREAD

**Issue by bjarkebm** [fog/fog-aws#500]
`Fog::Storage.get_body_size` returns 0 when `STDIN` is passed to it, e.g. when trying to create a file from `STDIN`:
`directory.files.create(:key => key, :body => STDIN, :multipart_chunk_size => 52428800)`

These line here:
https://github.com/fog/fog-aws/blob/d3c6cec347ce91a3c17325284b39295fd170e729/lib/fog/aws/models/storage/file.rb#L216-L222

will always call `put_object` which requires a seekable stream with a known size

The following error occurs::
```
/usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/storage.rb:660:in `pos=': Illegal seek @ rb_io_set_pos - <STDIN> (Errno::ESPIPE)
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/storage.rb:660:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/storage.rb:598:in `new'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/storage.rb:598:in `request'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/requests/storage/put_object.rb:46:in `put_object'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-aws-3.3.0/lib/fog/aws/models/storage/file.rb:220:in `save'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/fog-core-2.1.2/lib/fog/core/collection.rb:50:in `create'
	from ./aws_s3_upload.rb:175:in `s3_upload'
	from ./aws_s3_upload.rb:126:in `upload_content'
	from ./aws_s3_upload.rb:96:in `main_s3_uploader'
	from ./aws_s3_upload.rb:345:in `<main>'
```

**Comment by geemus** [comment]
@bjarkebm Sorry for the long delay. I'm not sure on this, I don't think I ever really had occasion to use STDIN in particular. Were you able to find a solution?
