### ISSUE TITLE
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden) 

### ISSUE THREAD

**Issue by Haseeb717** [fog/fog-aws#508]
Using `fog-aws` with `asset_async` to upload all assets on s3
When I try to async assets with s3 using command `AssetSync.sync` or `rake assets:precompile`

This throw an error

```
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
```
`:body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

Policy of IAM user

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::yallamotor-static-assets"
        },
        {
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::yallamotor-static-assets/*"
        }
    ]
}
```
`

How to fix this issue?

**Comment by geemus** [comment]
The only part that jumps out to me is that it appears to restrict most usage to the`yallamoter-static-assets` bucket. Can you double check that this is the bucket that is targeted in usage?

**Comment by mihado** [comment]
I have the same issue on 2 IAM users, one has `Administrator` role, the other one has `S3FullAccess` so I'm unsure what else should I try. thanks

**Comment by Haseeb717** [comment]
@geemus yes that bucket exists and I can manually upload, read files on it also

**Comment by geemus** [comment]
I'm not sure beyond that. I haven't used asset-sync, so that part of the equation is more mysterious to me. In general we haven't had any permissions related bugs reported against fog-aws recently, so perhaps you will have better luck asking on asset-sync itself? I'm guessing it might be something about usage/configuration of that in particular that your issues may be coming from. Does that make sense?

**Comment by chamnap** [comment]
@geemus, In my case, I didn't use `asset_sync` at all. However, I have to **uncheck** "Block all public access
" as shown in the following attachment. I'm not sure why. 
<img width="1319" alt="Screen Shot 2019-06-30 at 4 50 26 PM" src="https://user-images.githubusercontent.com/407708/60398117-e44dcf80-9b7e-11e9-9fa4-1739c90f26de.png">

**Comment by geemus** [comment]
@chamnap yeah, I'm not certain at this point either. Thanks for the information though, maybe that can help some of the other people that were having related issues.

**Comment by hopewise** [comment]
@here any update on this? the only I could access the bucket was to make it open:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DelegateS3Access",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::BUCKET_NAME/*",
                "arn:aws:s3:::BUCKET_NAME"
            ]
        }
    ]
}

**Comment by geemus** [comment]
@hopewise It looks likely to be either an asset-sync or fog-aws issue, rather than anything in excon per se (though the error is coming from excon). I'd suggest ensuring your asset-sync and fog-aws versions are up to date, and double check the credentials being used have the access levels you would expect. Beyond that I'm not sure where else to look/check/change.

**Comment by hopewise** [comment]
I did a debug for the used fog client, its `fog/1.41.0 fog-core/1.45.0` so, is it related?

**Comment by geemus** [comment]
I don't recall particular related bugs off hand, but fog/1.41.0 was released over 3 years ago and there have been a number of releases since then. Updating that, as well as fog-aws would probably be a good next step.
