### ISSUE TITLE
Support for AWS fargate

### ISSUE THREAD

**Issue by acatighera** [fog/fog-aws#510]
I had issues authenticating with AWS fargate (see error below). It seems like AWS support thinks that the IP address for fetching the credentials when using iam role needs to be changed (see their response below).

Error:
ActionView::Template::Error: Expected(200) <=> Actual(400 Bad Request)
excon.error.response
  :body          => ""
  :cookies       => [
  ]
  :headers       => {
    "Connection"        => "close"
    "Content-Type"      => "application/xml"
    "Date"              => "Thu, 14 Mar 2019 16:52:42 GMT"
    "Server"            => "AmazonS3"
    "Transfer-Encoding" => "chunked"
    "x-amz-id-2"        => "[redacted]"
    "x-amz-request-id"  => "[redacted]"
  }
  :host          => "[redacted].s3.amazonaws.com"
  :local_address => "[redacted]"
  :local_port    => [redacted]
  :path          => "[redacted].csv"
  :port          => 443
  :reason_phrase => "Bad Request"
  :remote_ip     => "[redacted]"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"

AWS Support Response:

"Furthermore, I am not sure why Fog fetched the credential from the address 169.254.169.254 which is the address for ec2 instance metadata [3] while for tasks using the Fargate launch type, the address of task metadata endpoint is 169.254.170.2 [3] and the credential is stored at “169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI” and your SDK will use the provided credentials to make calls to the AWS APIs. Please understand that we have no control of how Fog’s behavior of retrieving the credential in case "169.254.169.254" is hardcoded. "

**Comment by geemus** [comment]
Hey, thanks for the detailed report. I suspect this just hasn't happened to come up previously. You can see how we do the fetching presently here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/credential_fetcher.rb. I think previously we only ever needed the non-fargate option. So it seems likely we would want to add some kind of option here to switch between normal IAM and fargate. Does that make sense? Would you be up for helping to work on it?

**Comment by acatighera** [comment]
I might have some time to help. I will monkey patch it first to see if their recommended IP address actually works. If it does, I will submit a PR.

**Comment by acatighera** [comment]
AWS fargate is part of AWS ECS, it seems like there is already support for ECS? via the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI flag?

**Comment by geemus** [comment]
Possibly? I'm afraid I don't have any direct experience with it, so you are likely to know better than me. If that is true, maybe it is more a matter of improving documentation to clarify than changing code?

**Comment by acatighera** [comment]
It seems to be working now, so I don't think it requires any code changes! Closing this ticket.

**Comment by geemus** [comment]
Awesome, thanks for letting us know.

**Comment by acatighera** [comment]
update: The latest version of fargate platform 1.4.0 no longer needs the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI env var. In fact if you set it, it will break in 1.4.0.

**Comment by geemus** [comment]
Thanks for the update.
