### ISSUE TITLE
 Fog::DNS::AWS can't read zones

### ISSUE THREAD

**Issue by sugarb** [fog/fog-aws#513]
Running the following:
```ruby
fog_dns = Fog::DNS::AWS.new
fog_dns.zones
```

Results in:
TypeError: no implicit conversion of nil into String

**Comment by geemus** [comment]
Sorry to hear that. Could you share the stack trace to help point us more directly toward the area where the problem lies? Thanks!

**Comment by sugarb** [comment]
Unfortunately, there isn't one. I've tried several methods, and they all seem to be erroring with type error. We do provisioning with lots of other services, and we're tryign to upgrade the fog gem. This seems to be only happening with Fog::AWS::DNS.

```ruby
irb(main):009:0> begin
irb(main):010:1* fog_dns.zones
irb(main):011:1> rescue => e
irb(main):012:1> puts e; puts e.backtrace
irb(main):013:1> end
TypeError: no implicit conversion of nil into String
```

```ruby
irb(main):014:0> fog_dns.zones.all
TypeError: no implicit conversion of nil into String
```

```ruby
irb(main):017:0> fog_dns.list_hosted_zones
TypeError: no implicit conversion of nil into String
```

**Comment by sugarb** [comment]
Correction, I was able to get a backtrace.

```ruby
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-core-2.1.2/lib/fog/core/hmac.rb:22:in `digest'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-core-2.1.2/lib/fog/core/hmac.rb:22:in `block in setup_sha1'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-core-2.1.2/lib/fog/core/hmac.rb:14:in `sign'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-aws-3.4.0/lib/fog/aws/dns.rb:159:in `signature'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-aws-3.4.0/lib/fog/aws/dns.rb:128:in `request'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-aws-3.4.0/lib/fog/aws/requests/dns/list_hosted_zones.rb:39:in `list_hosted_zones'
REDACTED/shared/bundle/ruby/2.4.0/gems/fog-aws-3.4.0/lib/fog/aws/models/dns/zones.rb:15:in `all'
```

**Comment by sugarb** [comment]
@geemus I think this is just the change from Fog::DNS::AWS to Fog::DNS::AWS. Unfortunately it didn't give a deprecation warning.

**Comment by geemus** [comment]
Ah ha, yeah that sounds like a very likely candidate. I imagine if you change to Fog::AWS::DNS the issue does not occur? I'm not sure how easy (or not) it would be to retrofit a deprecation warning (as I have forgetten specifics of the original change).

**Comment by sugarb** [comment]
@geemus indeed it does. It looks as though it was supposed to:

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/dns.rb#L167

**Comment by geemus** [comment]
Ah, thanks for the reminder. The only thing I can think of would be if there is some require/load-order issue, that this code hasn't been required yet when you get the error (but I wouldn't expect that backtrace then). So... glad you have fixed your particular issue, but I'm not sure about how to fix the deprecation to reduce the chance of other people encountering it.

**Comment by sugarb** [comment]
@geemus since the deprecation doesn't work, perhaps remove it so at least they get an error that the class doesn't exist?

**Comment by geemus** [comment]
That makes sense to me.

@plribeiro3000 any objections? (I think you helped with the original renaming so may remember context I have forgotten).

**Comment by geemus** [comment]
Closing as I don't think we've seen further reports (and the code itself has changed enough that I'm not confident the problem still exists).
