### ISSUE TITLE
Missing AWS region: EU (Stockholm) eu-north-1

### ISSUE THREAD

**Issue by fred-secludit** [fog/fog-aws#514]
Hi guys,

AWS Stockholm region (eu-north-1) is missing from configuration files.
I checked the following file: fog-aws-3.4.0/lib/fog/aws.rb
I guess this should be added to it around line 219 in "@regions".

Please let me know if I can help. ;)

Thank you very much in advance.
Best regards,
Fred

**Comment by geemus** [comment]
Thanks for the heads up. If you'd like to create a pull request we would be happy to review and get that in.

**Comment by fred-secludit** [comment]
Hi Geemus ;)
I just created a pull request (Add AWS Stockholm region #515). I hope I did it properly otherwise please let me know.
Best regards

**Comment by geemus** [comment]
Looks great, thanks!

**Comment by geemus** [comment]
Released in v3.5.0
