### ISSUE TITLE
Path style is being deprecated

### ISSUE THREAD

**Issue by tedPen** [fog/fog-aws#516]
Wasn't able to find an issue for this but it looks like per Amazon S3's path style will be deprecated effective October 30th, 2020.

Might be worth removing that as an option. I would be willing to do this work if it's something you'd want to pursue.

Edit: Forgot to include source: [Official AWS announcement](https://forums.aws.amazon.com/ann.jspa?annID=6776)

**Comment by geemus** [comment]
Sure, I'm open to it. If I recall there are some characters allowed for bucket names that are not valid in subdomains though? If so, is there some escaping mechanism we need to think about?

**Comment by tedPen** [comment]
Looks like AWS considered that by updating their [naming restrictions](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)

>Amazon S3 no longer supports creating bucket names that contain uppercase letters or underscores. This change ensures that each bucket can be addressed using virtual host style addressing

**Comment by geemus** [comment]
Thanks for the deep link, that clarifies a lot. Seems like we could probably start working on removing this to simplify things then.

**Comment by tedPen** [comment]
AWS has backpedaled after feedback from customers: https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/. 

I think it makes sense to remove path_style as an option, but keep in place the existing fallbacks. I created a pull request with change, plan to follow up on tests.

**Comment by geemus** [comment]
@tedPen Sounds good, thanks for the PR and update.

**Comment by mzch** [comment]
I'd like to leave path_style as an option for S3 compatible storage, e.g. Minio.

**Comment by geemus** [comment]
@mzch ah yeah, that is a good call out. Thanks for the reminder.

**Comment by WilliamDenniss** [comment]
+1 to **keep** path_style. It hasn't been removed from AWS after all, and there are a lot of S3-compatible APIs. I need it for Minio too.

**Comment by geemus** [comment]
Closing this as we have good reasons to leave this as is, even if aws deprecates.
