### ISSUE TITLE
fog-aws: AWS extended length resource ID issues (8->18)

### ISSUE THREAD

**Issue by sysv** [fog/fog-aws#517]
Hello. I was using vagrant-was, and albeit unsupported, I noticed that the resource identifiers for aws-fog were not updated from 8 char to 18 (hex) char in response_parser.rb
 

/home/me/.vagrant.d/gems/2.4.4/gems/excon-0.64.0/lib/excon/middlewares/expects.rb:13:in `response_call': \

The image id '[ami-033a0960d9d83ead0]' does not exist (Fog::Compute::AWS::NotFound)

from /home/me/.vagrant.d/gems/2.4.4/gems/excon-0.64.0/lib/excon/middleware/response_parser.rb:12:in `response_call'

However, such object exists, and it would appear the 8 char pattern matching is suspect in fog-as 'compute.rb'

$  aws ec2 describe-images --image-id ami-033a0960d9d83ead0 

fog/fog-aws/blob/master/lib/fog/aws/compute.rb
--
Line 455: 
def tagged_resources(resources)
          Array(resources).map do |resource_id|
            if match = resource_id.match(/^(\w+)-[a-z0-9]{8}/i)

**Comment by geemus** [comment]
Thanks for the detailed report. Do you know if we need to support both 8 and 18 now, or has everything moved to 18? Thanks!

**Comment by sysv** [comment]
I’m pretty sure the 8 char AMI format is 
deprecated but still available for use

**Comment by geemus** [comment]
Yeah, it looks like all newly created resources will be in the longer format now, but that existing things might still be in the short format.

Here are some references in case we need to remind ourselves of the specifics in the future:
* https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html

**Comment by geemus** [comment]
@sysv thanks for the detailed report and feedback. I just pushed [a commit](https://github.com/fog/fog-aws/commit/ab029cf025dedce3fed09982afbc0e3ec06569db) with a loosened regex to see if that will solve the problem. Technically it is overly loose (it would accept anything from 8-17 characters), but that is a lot simpler than checking specifically for the two lengths and I don't forsee it being problematic. Could you try things out with the patch and see if it resolves your issue? Thanks!

**Comment by sysv** [comment]
Give me until next week to verify
On vacation (NOP NOP,...) thanks sysv

**Comment by geemus** [comment]
@sysv Sure thing, thanks for the update.

**Comment by jeremywadsack** [comment]
There's another issue in the `Mock` for spot instances that is still expecting an 8-character ID:

https://github.com/fog/fog-aws/blob/0080b9813796b69a5ffeb242973c0431117334d4/lib/fog/aws/requests/compute/request_spot_instances.rb#L116-L119

**Comment by geemus** [comment]
Thanks for the heads up, here is the fix: https://github.com/fog/fog-aws/commit/f19f102cfa010975b66e8ed47e02d29d8ca7bd5a
