### ISSUE TITLE
fog-aws: Fog::AWS::Glacier::Job doesn't support RetrievalByteRange

### ISSUE THREAD

**Issue by hkmaly** [fog/fog-aws#519]
Looking at https://docs.aws.amazon.com/amazonglacier/latest/dev/api-initiate-job-post.html#api-initiate-job-post-requests it seem to be possible, on job creation, to specify that you only want to retrieve part of archive using the RetrievalByteRange option. This option is not present in Fog::AWS::Glacier::Job::save. There is option to retrieve just part of file in get_output, but I suspect at that point you will get billed for whole file anyway.

**Comment by geemus** [comment]
@hkmaly Thanks for the heads up. It may be that nobody happened to need this previously, so we overlooked it (or perhaps the available options changed). In any event, I'd be open to improving this. Would you be interested in working on a pull request to add the option? I'm certainly happy to discuss and support that however I can. Thanks!

**Comment by hkmaly** [comment]
Interested, yes, however I'm not sure if I get to it anytime soon.
Adding the option itself would be easy, but ideally the gem should also prevent you from downloading range you didn't retrieved.

**Comment by geemus** [comment]
K, thanks for letting me know. We could perhaps start with supporting the option and work on the prevention later on.
