### ISSUE TITLE
Fog::AWS::Glacier::TreeHash::add_part works only sometimes

### ISSUE THREAD

**Issue by hkmaly** [fog/fog-aws#520]
You can easily test that from following three codes, only two returns same (presumably correct) result. And it would get even worse if the parts are not multiples of megabyte. Now, I suppose code using this internally is written so it always works correctly ... if the part size is correct ... and the input io doesn't do some weird buffering ... but in my opinion, the code should either work correctly or raise exception if some of those assumptions are broken, and never return incorrect value.
```
tree_hash = Fog::AWS::Glacier::TreeHash.new
tree_hash.add_part('x' * 1024*1024)
tree_hash.add_part('y' * 1024*1024)
tree_hash.add_part('z' * 1024*1024)
tree_hash.add_part('t' * 1024*1024)
tree_hash.hexdigest
```
```
tree_hash = Fog::AWS::Glacier::TreeHash.new
tree_hash.add_part( ('x' * 1024*1024) + ('y' * 1024*1024) + ('z' * 1024*1024))
tree_hash.add_part('t' * 1024*1024)
tree_hash.hexdigest
```
```
tree_hash = Fog::AWS::Glacier::TreeHash.new
tree_hash.add_part( ('x' * 1024*1024) + ('y' * 1024*1024) + ('z' * 1024*1024) + ('t' * 1024*1024))
tree_hash.hexdigest
```

**Comment by geemus** [comment]
I've never personally used this (or glacier for that matter), so unfortunately I'm not super familiar with expectations around any of it. Maybe we could start with adding some failing stuff to https://github.com/fog/fog-aws/blob/master/tests/requests/glacier/tree_hash_tests.rb ? That way it's abundantly clear what expectations are, and where they are breaking. What do you think?

**Comment by hkmaly** [comment]
I think I will make a pull request for this one. I've got idea how to fix it which was so surprisingly easy (relatively) I failed to resist temptation to try that. Also, unlike #519, this one couldn't cost money to test.

**Comment by geemus** [comment]
Sounds good, thanks!
