### ISSUE TITLE
Support for Hong Kong Region (ap-east-1)?

### ISSUE THREAD

**Issue by tisba** [fog/fog-aws#527]
Hi there 👋 

I just noticed, that apparently aws-fog does not yet support `ap-east-1` (Hong Kong). See steps to reproduce below.

I have two questions:

1. I can imagine that it's probably not very simple to add a new regions, especially `ap-east-1` is a "special" region; BUT is there a way to add a region by patching aws-fog? I'm looking at https://github.com/fog/fog-aws/blob/06c82d392fcdf83479cce899aefab5b588850b49/lib/fog/aws.rb#L219-L235 but I'm not sure if this is a good idea or not.
1. What is the "usual" process for new regions to be added? I'm happy to help if I can.

Steps to reproduce:

```ruby
Fog::Compute.new(provider: :aws, region: "ap-east-1", aws_access_key_id: "key", aws_secret_access_key: "secret")
```

fails with

```
ArgumentError: Unknown region: "ap-east-1"
from /srv/www/forge/shared/bundle/ruby/2.6.0/gems/fog-aws-3.5.1/lib/fog/aws.rb:239:in `validate_region!'
```

**Comment by geemus** [comment]
Historically it's been as simple as adding a region to the list in file you referenced. If you'd like to make a pull request for that, we should probably be able to get it update pretty quickly. It's possible there are other issues we might run into, but with the existing regions it has always been as easy as that. Thanks!

**Comment by tisba** [comment]
Oh, great. I'll look into this. I cannot recall exactly where I found an overview of `ap-east-1` differences. But I'm happy to check with AWS Services we use (mostly EC2 and S3).

**Comment by tisba** [comment]
Sorry, I should just had given this a try. As you've said, it just works 🎉  see #528.
