### ISSUE TITLE
filename too long

### ISSUE THREAD

**Issue by eloyfernandes** [fog/fog-aws#544]
I'm using sidekiq to upload xlsx to AWS, then read them to import the data to my project, but I'm having an issue since several days ago when I changed from the gem fog 1.38 to the gem fog-aws  3.5. 

When I upload the xlsx sidekiq throws me the next error:

> Errno::ENAMETOOLONG: File name too long @ dir_s_mkdir - /tmp/roo_excel_format.xlsx?X-Amz-Expires=604700&X-Amz-Date=20200117T142942Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJQXG4LPHFKFAHHZ...

For some context, I always replace the filename of the file to "excel_format.xlsx" before uploading it to aws, that's because I won't need to store all the files, just read them and get the data.

But I'm noticing that the file name "concats" aws signatures, like "Amz-Expires" "Amz-date", "Amz-Aggorithm" etc...

Why this could be happening? I tried reproducing the error locally but it didn't work, on my machine, the file uploaded fine and I got all the data correctly.

**Comment by geemus** [comment]
That looks like a temporary-access url generated from S3 (where the parameters include the signing information to provide access). It looks like it may be trying to use that full url as the local filename and is failing then? Does that sound like it could be the case? Without seeing some parts of the code it's a bit hard for me to say why it would be doing that though.

**Comment by eloyfernandes** [comment]
Hi, sorry I took so long to respond, I was trying everything first but I gave up.

Here's my code:

> Here I receive the file from the front end and proceed to upload it using carrierwave.

```
  def import_services_with_excel
    file = params[:settings][:file] if params[:settings]

    country_id = @current_user.country_id

    if file
      uploader = TemporaryFileUploader.new(country_id)

      begin
        uploader.store!(file.tempfile)
      rescue CarrierWave::IntegrityError
        flash[:notice] = t('general.no_extention', extention: "[xls|xlsx]")
        redirect_to import_services_settings_path
        return
      end

      worker_params = { country_id: country_id,
                        current_user: @current_user.id,
                        original_filename: file.original_filename }

      ImportServicesExcelWorker.perform_async(uploader.filename, worker_params, load_api_token)

      flash[:success] = t('settings.start_import')
      redirect_to import_services_settings_path
    else
      flash[:notice] = t('general.no_import_file')
      redirect_to import_services_settings_path
    end

  end

```

> Here's the file uploader using carrierwave.

```
class TemporaryFileUploader < CarrierWave::Uploader::Base

  attr_accessor :country_id

  def initialize(country_id)
    @country_id = country_id
  end

  def store_dir
    if Rails.env.production?
      "#{ENV['APP_NAME']}/uploads/formats/#{@country_id}"
    else
      "uploads/tmp/excel/"
    end
  end


  # Add a white list of extensions that are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
    ['xlsx', "xls"]
  end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  def filename
    "excel_format." + original_filename.split(".").last if original_filename
  end

end
```

For more context, I have carrier wave version 1.3.1

Please help. 

Thanks.

**Comment by geemus** [comment]
From that, I would guess the issue might be with the filename method. Do you know how/where `original_filename` is being populated?

**Comment by eloyfernandes** [comment]
I fix it. it was a problem with another gem (roo),, sorry about this issue.

**Comment by geemus** [comment]
No worries, thanks for the update.
