### ISSUE TITLE
Class name typo: AssumeRoleWithWithWebIdentity

### ISSUE THREAD

**Issue by dgoradia** [fog/fog-aws#548]
In `lib/fog/aws/parsers/sts/assume_role_with_web_identity.rb` the class is named `AssumeRoleWithWithWebIdentity`, is that a typo?

Should it be named `AssumeRoleWithWebIdentity` instead? (Note WithWith instead of With)
as it's used here: `lib/fog/aws/requests/sts/assume_role_with_web_identity.rb`

**Comment by geemus** [comment]
Yes, that sounds likely to be a typo. Would you be up for a quick pull request to fix it? Thanks!

**Comment by dgoradia** [comment]
Sure opened PR #549

**Comment by geemus** [comment]
Thanks!
