### ISSUE TITLE
Is fog-aws compatible with AWS Trust Services?

### ISSUE THREAD

**Issue by caseyli** [fog/fog-aws#558]
I've been following up on an email that Amazon sent out concerning their move using their own certificate manager (ACM) which uses Amazon Trust Services as their root authority. To prep for the transition, they have this article:

https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/

It talks about verifying compatibility with apps, SDKs, and CLI.

I know `fog-aws` doesn't use the SDK, so I'm just curious if `fog-aws` will have any issues with the move. Is there a certain version we need to be on to make sure we're ok for this transition?

Thanks!

**Comment by geemus** [comment]
Thanks for checking in and sharing details. By default fog relies on the certs bundled with excon, which in turn are regularly updated to match Mozilla/Firefox. The article you mention suggests all the browsers should already be compatible, so to the best of my knowledge we will be as well.

**Comment by caseyli** [comment]
Great! Thanks @geemus for the quick response!
