### ISSUE TITLE
Fog Logs?

### ISSUE THREAD

**Issue by memotoro** [fog/fog-aws#561]
Hello @geemus . This is not an issue, it is actually a question. Is it possible to perform via fog the same operations as the [aws cli logs](https://docs.aws.amazon.com/cli/latest/reference/logs/index.html) Just wondering if I can use fog to push data to a particular log group but I cannot see anything obvious.

Any help would be nice. Thanks

**Comment by geemus** [comment]
There are some cloudwatch things implemented, but it doesn't look like we have full coverage (and I'm not seeing logs at present). You can see the requests that we already support in this directory: https://github.com/fog/fog-aws/tree/master/lib/fog/aws/requests/cloud_watch

We would certainly be open to supporting the log requests also, I just don't think anyone has gotten to it quite yet (we tend to add things as they are needed). I'd certainly be happy to support work on them if you are interested. Thanks!

**Comment by memotoro** [comment]
Thanks @geemus I was looking those file in requests but I wanted to make sure that I wasn't missing anything. Thanks a log. I'll have a look to see if it is something I can do and I'll create a PR. Thanks a lot. Regards

**Comment by memotoro** [comment]
Hi @geemus I'll close the bug as it is not an actual error in code. Regards

**Comment by geemus** [comment]
Sounds good, thanks.
