### ISSUE TITLE
Duplicate compute flavours

### ISSUE THREAD

**Issue by abrom** [fog/fog-aws#563]
It looks like #555 has introduced some duplicate r5 compute flavours:
```
> Fog::AWS::Compute::Flavors.new.all.group_by(&:id).select { |id, flavors| flavors.length > 1 }.transform_values { |values| values.map(&:name) }
=> {"r5.8xlarge"=>["R5 Eight Extra Large", "R5 Octuple Extra Large"],
     "r5.12xlarge"=>["R5 Twelve Extra Large", "R5 Sixteen Extra Large"]}
```

Note there was already an `r5.8xlarge` named `R5 Octuple Extra Large` and the entry named `R5 Sixteen Extra Large` appears to have an ID of `r5.12xlarge` (there is already an `r5.12xlarge`). As such I suspect #555 should just be reverted.

On a side note, I see there are a number of instance types where the name is maybe a bit generic (ie prefix with the family type?). As well as the `u-6tb1.metal` entry which should probably be named `U 6 TB Metal` ??  See:

```
> Fog::AWS::Compute::Flavors.new.all.group_by(&:name).select { |id, flavors| flavors.length > 1 }.transform_values { |values| values.map(&:id) }
=> {"Micro Instance"=>["t1.micro", "t2.micro"],
 "Small Instance"=>["t2.small", "m1.small"],
 "Medium Instance"=>["t2.medium", "m1.medium"],
 "Large Instance"=>["t2.large", "m1.large"],
 "Extra Large Instance"=>["t2.xlarge", "m1.xlarge"],
 "R5 Sixteen Extra Large"=>["r5.12xlarge", "r5.16xlarge"],
 "X1e Sixteen Extra Large"=>["x1e.16xlarge", "u-6tb1.metal"]}
```

Happy to put together a PR if the above sounds right :)

**Comment by geemus** [comment]
Sounds reasonable to me. A PR would be great, thanks!
