### ISSUE TITLE
Fog::Compute::AWS is deprecated, please use Fog::AWS::Compute warning

### ISSUE THREAD

**Issue by apuntamb** [fog/fog-aws#565]
@geemus Hello! 
In foreman, I have the correct definition `Fog::AWS::Compute` specified everywhere. For reference, check one of the definitions [here](https://github.com/theforeman/foreman/blob/6cb37796283412fc35d348f42a9ac35e41a076d7/app/models/concerns/fog_extensions.rb#L9-L15). I have also updated to the latest fog-aws version i.e. `3.6.4` but, still I can see the deprecation warning. The `fog-core` that I have is 2.1.0.
Let me know if I'm missing here something or if the warnings are always shown.

**Comment by geemus** [comment]
Hmm. I don't think they should always be shown, but I could be wrong. Could you share what the warnings are looking like for you?

**Comment by apuntamb** [comment]
Yeah sure! This is the exact warning message:
`[fog][DEPRECATION] Fog::Compute::AWS is deprecated, please use Fog::AWS::Compute.` which seems to be generated from [here](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/compute.rb#L669).

**Comment by apuntamb** [comment]
Also, in addition to this there is one more warning message shown and that is:
`[fog][WARNING] Unrecognized arguments: aws_access_key_id, aws_secret_access_key, region`. Both of these are always shown together.

**Comment by kgaikwad** [comment]
> Also, in addition to this there is one more warning message shown and that is:
> `[fog][WARNING] Unrecognized arguments: aws_access_key_id, aws_secret_access_key, region`. Both of these are always shown together.

@geemus, correct me if I am wrong.
This may related to how you connect. Try connection using `Fog::AWS::Compute.new` instead of `Fog::Compute.new`.  
Let us know if you are still getting those warnings.

**Comment by apuntamb** [comment]
@kgaikwad Yes, creating client object using `Fog::AWS::Compute.new` works.  No warnings shown. @geemus is that the correct usage?

**Comment by geemus** [comment]
@apuntamb Oops, yeah I hadn't put it all together quite yet, but reviewing this I would agree with @kgaikwad explanation. Our intention was to deprecate the more generic `Fog::Compute.new` in favor of the more specific usage as this better facilitates splitting up the gems. So yes, this is the expected usage and should not give deprecation warnings. If you have suggestions on how to make the deprecation warning clearer to help others avoid this confusion I'd certainly welcome it.

@kgaikwad thanks for helping out, I think you got it exactly right.
