### ISSUE TITLE
Add support for r6g and c6g instance types

### ISSUE THREAD

**Issue by calebwoofenden** [fog/fog-aws#580]
Right now fog-aws only supports m6g, not r6g or c6g. Is there any reason they haven't been added? If not I could stage a PR to add their specs into flavors.rb.

**Comment by geemus** [comment]
@calebwoofenden thanks for checking in. I think the only reason is probably that nobody needed it yet and/or nobody has gotten around to it yet. If you'd like to put together a PR that would be great!
