### ISSUE TITLE
Fog does not return error from s3

### ISSUE THREAD

**Issue by georgebancila** [fog/fog-aws#586]
I am having a really strange issue. I am using fog-aws to connect to a s3 storage. I specify that I am **not** using the `use_iam_profile` option, therefore the credentials will not be refreshed by fog. 

This happens in a sidekiq job so if I would receive an error the job would be retried. I see this error in datadog traces `Excon::Error::BadRequest: Expected(200) <=> Actual(400 Bad Request) excon.error.response :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message>` but I am not receiving that error in my backend. Any ideas?

**Comment by geemus** [comment]
I'm not sure off hand. Could you say more about what request(s) might be failing? That might help narrow it down.

**Comment by georgebancila** [comment]
I'm just trying to get a file from an s3 bucket.
```
storage = Fog::Storage.new(provider: 'AWS',
                         region: aws_region,
                         aws_access_key_id: access_key_id,
                         aws_secret_access_key: secret_access_key,
                         aws_session_token: session_token,
                         aws_credentials_expire_at: expiration)

storage.directories.get(dir_name).files.get(file_name)
```

**Comment by geemus** [comment]
Hmm. From the looks of that it seems as though the session_token you are providing is ending up (in some cases) expiring. If this is inside a long-running process, maybe it lasts long enough to no longer be valid? How/where are you refreshing those tokens?

**Comment by georgebancila** [comment]
I know, that's exactly what is happening. I don't specifically refresh it, the sidekiq job that I have is expected to fail if that happens and it will be retried with refreshed certification. My problem is that I don't receive any error when I make that last call.

**Comment by geemus** [comment]
K. Do you mean when you manually/directly make that call you don't get an error? Is it possible you are using different session/token information?

**Comment by georgebancila** [comment]
yes, when i make that call, I don't get an error back in the context. Although I can see the traces in Datadog. I'm not sure what you mean about different session/token info..

**Comment by geemus** [comment]
@georgebancila sorry, I'll try to clarify. You said you did get the error from sidekiq, but not when making the call directly. The code you posted appears to be passing the was key/id as well as session information. I was wondering if the session token you would be passing inside sidekiq and the session token you are using directly are different? Especially as the error appears to refer to this token. Does that make more sense?
