### ISSUE TITLE
Fog::AWS::Storage timeout against S3

### ISSUE THREAD

**Issue by mepatterson** [fog/fog-aws#599]
I've setup fog-aws to connect to my S3 bucket using access key/secret. This works perfectly from my local development machine.

But deployed to my server (ECS containerized instance), it simply times out on any attempt to do anything. `client.directories` just sits there forever and eventually throws `Excon::Error::Timeout: connect_write timeout reached`

I have a task role set on my containers that provides S3 FullAccess. I'm using credentials that I know work (because I can use them locally). I know the security group for my container allows outbound to 80 and 443. What else could I be missing that would prevent an ECS task instance from communicating with S3? It's not giving me any permission errors... it just seems like it can't connect to anything... ?

**Comment by geemus** [comment]
@mepatterson Hey, sorry to hear that. I don't know off hand, but here are some initial ideas of things we can do to try and narrow it down:

* Are you able to make other http requests successfully, or do all attempts to connect timeout?
* Are you using the same versions of excon/fog-aws and ruby locally and in ECS?

**Comment by mepatterson** [comment]
Of course, this turns out to be a dumb ECS misconfiguration on my part. For anyone else's reference, if you have "awsvpc" networking mode turned on for an ECS instance, it may block you from accessing S3 and other external websites. I reconfigured things and now it works fine. Thanks for pointing me in the right direction.

**Comment by geemus** [comment]
No worries, glad you found a fix!
