### ISSUE TITLE
Support for Regional STS Endpoints

### ISSUE THREAD

**Issue by MichaelGerhart** [fog/fog-aws#604]
based on https://github.com/fog/fog-aws/blob/f381dd7166d048934d22cb4480235e9f311566f1/lib/fog/aws/credential_fetcher.rb#L16 and  https://github.com/fog/fog-aws/blob/f381dd7166d048934d22cb4480235e9f311566f1/lib/fog/aws/credential_fetcher.rb#L47 

It would seem fog-aws cannot currently support regional STS endpoints. This is a deal breaker in organizations that lock down global endpoints in favor of regional endpoints where they exist.

fog-aws should have logic that handles whether or not the environment variable "AWS_STS_REGIONAL_ENDPOINTS" exists with the value "regional" and is matched with the value of "AWS_REGION".

**Comment by geemus** [comment]
Thanks for the heads up. Something along those lines definitely sounds reasonable. Would you be willing and able to work on a patch to fix this? Thanks!

**Comment by MichaelGerhart** [comment]
@geemus Yeah! It shouldn't be overly complicated, I'll get something together and open a PR.

**Comment by geemus** [comment]
@MichaelGerhart - Yeah, seems pretty straightforward, I just don't think it had come up for anyone yet (that I'm aware of anyway). Just let me know if you have questions or anything I can help with along the way.

**Comment by MichaelGerhart** [comment]
Thanks @geemus I just to a whack at it, let me know what you think.
