### ISSUE TITLE
Using Hitachi compatible S3 and still see the AWS S3 host 

### ISSUE THREAD

**Issue by meraj-kashi** [fog/fog-aws#624]
I am trying to use Fog to connect to an internal Hitachi compatible S3 (custom host).

The connection failed with "Excon::Error::Forbidden" and looking at the output the host still bind to s3.amazonaws.com. I read the same problem [here](https://github.com/fog/fog-aws/issues/575), could you support how to use internal host within the Fog conection?

```
require 'rubygems'
require 'fog/aws'

connection = Fog::AWS::Storage.new({
  :aws_access_key_id        => 'xxxxxxxxxxxxxxx',
  :aws_secret_access_key    => 'xxxxxxxxxxxxxxxxxxxxxx',
  :region                   => 'us-east-1',
  :host                 => "https://our-hitach-s3-url:443",
  :path_style               =>  true,
})

# list directories
p connection.directories
```

The below is the output:

```
usr/local/bundle/gems/excon-0.87.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected(200) <=> Actual(403 Forbidden) (Excon::Error::Forbidden)
excon.error.response
  :body          => "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>xxxxxxxxxxxxx</AWSAccessKeyId><RequestId>3J11N4DD9W2VFAYS</RequestId><HostId>4g8/Gnq3ixaQoBAfLxytiLj21MkoPrt3xMLz8ujOtSEwXwmGBYmK+jYitKHdbuU4XZ9gsGDJj3Y=</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Content-Type"     => "application/xml"
    "Date"             => "Fri, 22 Oct 2021 12:17:24 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "4g8/Gnq3ixaQoBAfLxytiLj21MkoPrt3xMLz8ujOtSEwXwmGBYmK+jYitKHdbuU4XZ9gsGDJj3Y="
    "x-amz-request-id" => "3J11N4DD9W2VFAYS"
  }
  :host          => "s3.amazonaws.com"
  :local_address => "172.17.0.2"
  :local_port    => 49020
  :path          => "/"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "52.216.250.62"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\\r\\n"
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/connection.rb:451:in `response'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/connection.rb:282:in `request'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/middlewares/base.rb:17:in `error_call'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/middlewares/base.rb:17:in `error_call'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/connection.rb:307:in `rescue in request'
        from /usr/local/bundle/gems/excon-0.87.0/lib/excon/connection.rb:227:in `request'
        from /usr/local/bundle/gems/fog-xml-0.1.4/lib/fog/xml/sax_parser_connection.rb:29:in `request'
        from /usr/local/bundle/gems/fog-xml-0.1.4/lib/fog/xml/connection.rb:7:in `request'
        from /usr/local/bundle/gems/fog-aws-3.12.0/lib/fog/aws/storage.rb:668:in `_request'
        from /usr/local/bundle/gems/fog-aws-3.12.0/lib/fog/aws/storage.rb:663:in `request'
        from /usr/local/bundle/gems/fog-aws-3.12.0/lib/fog/aws/requests/storage/get_service.rb:21:in `get_service'
        from /usr/local/bundle/gems/fog-aws-3.12.0/lib/fog/aws/models/storage/directories.rb:10:in `all'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/core/collection.rb:112:in `lazy_load'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/core/collection.rb:16:in `map'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:85:in `inspect_object'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:72:in `block in nested_objects_string'
        from /usr/local/bundle/gems/formatador-0.3.0/lib/formatador.rb:92:in `indent'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:41:in `indent'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:72:in `nested_objects_string'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:54:in `object_string'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:14:in `block in format'
        from /usr/local/bundle/gems/formatador-0.3.0/lib/formatador.rb:92:in `indent'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:41:in `indent'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/formatador.rb:14:in `format'
        from /usr/local/bundle/gems/fog-core-2.1.0/lib/fog/core/collection.rb:72:in `inspect'
        from fogaws.rb:15:in `p'
        from fogaws.rb:15:in `<main>'
```

**Comment by bak1an** [comment]
Having the same issue when using B2 S3 compatible API. It still goes to `s3.amazonaws.com` and gets 403 even though there is `endpoint: 'https://s3.us-west-002.backblazeb2.com'`

**Comment by bak1an** [comment]
Updating `get_service` as described in https://github.com/fog/fog-aws/issues/575 works fine.

**Comment by geemus** [comment]
@bak1an Thanks for the update, glad to hear you found a fix. Just let me know if you'd like to work on a patch to fix this more generally, similar to the discussion in #575 as I'd be happy to support that.

**Comment by bak1an** [comment]
@geemus I can create a patch to fixup this. Will be able to get to it in about 3 weeks.

**Comment by geemus** [comment]
@bak1an Sounds great, just let me know if you need anything when you get to it.

**Comment by max-critcrew** [comment]
@geemus @bak1an Has this ever been patched/fixed? I'm currently trying to get this to work with a self hosted GitLab & ObjectStorage + Backblaze and I'm getting the exact same error. The URI contains amazonaws.com even though it should not.

In case there's no official fix: Do you have any pointers what I can do to fix my local fog-aws if needed?

Any helps is super appreciated :)

**Comment by geemus** [comment]
@max-critcrew I think the particular issue I was aware of was fixed here: https://github.com/fog/fog-aws/commit/cf564b97077c7d468860c2549e3372291b004d39.

It's certainly possible there are other/remaining issues though.

Could you open a new issue with a bit more detail of which calls in particular you are calling that have the wrong URI and what settings you are sending in? (please be sure to sanitize/strip any credentials before sharing, but knowing what endpoint/host info you are passing in should help narrow it down. Thanks!

**Comment by max-critcrew** [comment]
@geemus Thanks for your response! :)

I think I actually figured it out, but I'm not 100% sure. After like 5-6 hours of trying and debugging locally - it turns out that if you do anything slightly wrong in your configuration - it seems like you're not getting an error message, but instead your url simply gets replaced to an amazon URL.

This maybe (I'm not entirely sure yet if anything can breatk) works for us now:

`connection = Fog::Storage.new(
  {
    provider: 'AWS',
    region: 'UNUSED',
    endpoint: 'https://s3.eu-central-XXX.backblazeb2.com',
    aws_access_key_id: 'ACCESS_KEY',
    aws_secret_access_key: 'SECRET_KEY'
  }
)`

If you (for example) do not put "https://" at the start of the endpoint (which backblaze themself also does not do, they just show `s3.eu-central-XXX.backblazeb2.com`), the URL gets replaced.

I hope this helps. If you want to, I can also open another issue to further discuss/explain? :)
