### ISSUE TITLE
Add a special note to the documentation around the danger of using directory.get

### ISSUE THREAD

**Issue by orrin-naylor-instacart** [fog/fog-aws#633]
Hi,
We here at instacart recently realized we were using your gem incorrectly.
We've been using `directory.get` for creating and downloading files.
After switching to `directory.new` we estimate our ads export jobs will save over 2 years of compute time per month!!! We were literally wasting a whole years worth of compute time every two weeks fetching and parsing the 10,000 files metadata. Just to have it immediately thrown away.  That's just fixing one implementation. We have 56 more to go!!!

[If you're interested here's our discovery.](https://docs.google.com/document/d/1HR1lUHOG2Q4jju5DdT6XlTCCLp_f67c_WhFSBjjZgB4/edit?usp=sharing)

I think it would make a major impact on climate change(hehe) to add a note telling people they really don't want to use `directory.get`, unless they need to.

**Comment by geemus** [comment]
Thanks for sharing and the detailed write-up. I'm both sorry to hear you ran in to this problem in the first place and pleased you realized and were able to overcome it. It certainly wasn't meant to be a secret or surprising, but it definitely ended up being subtle enough to be very easy to overlook.

I would certainly be happy to improve the documentation to help others avoid this error. Do you have suggestions about where we could/should put this to make it more likely that people would find and understand it at the right times? I'd welcome suggestions or PRs you might have to that effect.

**Comment by orrin-naylor-instacart** [comment]
Sounds good! LMK if this is too heavy handed, or you can think of a better phrasing.
https://github.com/fog/fog-aws/pull/634

**Comment by orrin-naylor-instacart** [comment]
Might be worth adding a note
here https://www.rubydoc.info/github/fog/fog-aws/Fog/AWS/Storage/Directories#get-instance_method
and here https://www.rubydoc.info/github/fog/fog-aws/Fog/AWS/Storage/Directories#get-instance_method

How do I edit these docs?

**Comment by orrin-naylor-instacart** [comment]
Turns out I'm terrible at using github 🤦 .

LMK if this is too much, or if you can think of better phrasing.
https://github.com/fog/fog-aws/pull/635

**Comment by geemus** [comment]
Seems fine to me, we can always tweak or refine it later too if we think of something better or others have suggestions.
