### ISSUE TITLE
Documentation links broken / 404

### ISSUE THREAD

**Issue by awongh** [fog/fog-aws#642]
The links in the readme to the ruby doc page seem to be broken.

This line: https://github.com/fog/fog-aws/blob/master/README.md?plain=1#L173

points to this page, which 404s: https://www.rubydoc.info/github/fog/fog-aws

**Comment by geemus** [comment]
@awongh thanks for the heads up. Unfortunately it seems that if I try to follow the link it resolves to a page as I would expect, so I was unable to verify the 404 behavior or fix it. Perhaps it was a temporary problem, could you try again and see if you are still encountering this problem? Thanks!

**Comment by awongh** [comment]
Yes, seems like it was a temporary problem with rubydoc? Seems resolved, thank you 🙏
