### ISSUE TITLE
Unable to list, update and remove RDS tags in AWS GovCloud Account regions.

### ISSUE THREAD

**Issue by svavhal** [fog/fog-aws#644]
Unable to list, update and remove RDS tags in  AWS GovCloud Account regions.

Amazon Resource Name (ARN) format which we get in AWS US gov regions is different from all other AWS regions

**fog-aws version used: 3.13.0**
agent.add_tags_to_resource
agent.list_tags_for_resource
agent.remove_tags_from_resource

Getting this issue
Fog::AWS::RDS::Error: InvalidParameterValue => Invalid resource name: "resource name"
  from lib/fog/aws/requests/rds/list_tags_for_resource.rb:16:in `list_tags_for_resource'}
  
  Pull request for thie issue https://github.com/fog/fog-aws/pull/643

**Comment by geemus** [comment]
Thanks for the heads up, I'll review and give feedback presently.
