### ISSUE TITLE
S3: File copy not working outside us-east-1 region

### ISSUE THREAD

**Issue by johnnyshields** [fog/fog-aws#645]
Attempting to copy files to an S3 bucket outside `us-east-1` region appears to be broken. I tried things like passing in the region into the `options` arg, but no dice.

```
bucket.files.first.copy(bucket.key, "some_path")

/opt/app/vendor/bundle/ruby/3.0.0/gems/excon-0.92.2/lib/excon/middlewares/expects.rb:13:in
`response_call': Expected(200) <=> Actual(400 Bad Request) (Excon::Error::BadRequest)
excon.error.response
  :body          => "<Error>
<Code>AuthorizationHeaderMalformed</Code>
<Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-northeast-1'</Message>
<Region>ap-northeast-1</Region>
<RequestId>93VRH5HDA2A0CG4N</RequestId>
<HostId>F+Qzb6KWTfn...gNQoWRv8=</HostId
</Error>"
```

**Comment by geemus** [comment]
Are you setting the `ap-northeast-1` region when making the connection? I think that might be where the header values come from (and `us-east-1` is the default if I recall). I think setting it at that level should probably allow it to flow through and appear here, but do let me know if that is what you are already doing or if it just doesn't work the way I recall.
