### ISSUE TITLE
superclass mismatch for class AWS

### ISSUE THREAD

**Issue by vahtel** [fog/fog-aws#655]
fog-aws doesn't work with  fog-core  2.3.0.  It gives an error:

```
storage.rb:831:in `<module:Storage>': superclass mismatch for class AWS (TypeError)
```

Example

```
Loading development environment (Rails 6.1.7)
3.0.3 :001 >         s3 = Fog::Storage.new(
3.0.3 :002 >           :provider => 'AWS',
3.0.3 :003 >           :aws_access_key_id => S3_UPLOADER_ACCESS_KEY,
3.0.3 :004 >           :aws_secret_access_key => S3_UPLOADER_SECRET_ACCESS_KEY
3.0.3 :005 >         )
/Users/rene/.rvm/gems/ruby-3.0.3/gems/fog-aws-3.15.0/lib/fog/aws/storage.rb:831:in
 `<module:Storage>': superclass mismatch for class AWS (TypeError)
```

Works when downgrading to fog-core 2.2.4

**Comment by geemus** [comment]
Unfortunately, I've not had much luck in reproducing this. If I open irb with those fog-aws and fog-core versions, it seems to work as I would expect. I wonder if there is some kind of interaction with something else in your environment, or perhaps I'm just doing something wrong or differently. Could you try to create a more stripped down reproduction case to help me pin this down? In particular, if it could isolate to just fog-aws/fog-core that would really help narrow it down. Thanks!

**Comment by vahtel** [comment]
After upgrading to ruby 3.0.4 it started to work. Strange.
