### ISSUE TITLE
Is there an equivalent to describe-instance-status?

### ISSUE THREAD

**Issue by troelskn** [fog/fog-aws#66]
I'm looking for an equivalent to [`describe-instance-status`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-status.html) - `status` returns "running" when the instance is up, but I would like to wait until status checks have passed before proceeding. It doesn't look like there is a way to get this information currently, but maybe I'm missing it?

**Comment by troelskn** [comment]
After hacking around the source a bit, I have monkey patched my way to this:

```
module FogHack
  def instance_status
    data = service.describe_instance_status('InstanceId' => identity).body["instanceStatusSet"].first
    if data && data["instanceStatus"]
      data["instanceStatus"]["status"]
    end
  end
end

require 'fog/aws/models/compute/server'
Fog::Compute::AWS::Server.__send__ :include, FogHack
```

which essentially does what I need. Is it something you would accept a pull request for?

**Comment by geemus** [comment]
I guess I've usually just used describe_instances directly (or indirectly via `servers.get`) and then just used the `status` attribute there to see if it was running or what have you. Is there reason to use this method instead? (pardon my lack of familiarity, I just don't know much about this way of doing it). Thanks!
