### ISSUE TITLE
FOG::AWS::Compute::Mock doesn't respect or return tags defined as TagSpecifications objects

### ISSUE THREAD

**Issue by thorrsson** [fog/fog-aws#667]
TagSpecitications were added in https://github.com/fog/fog-aws/pull/610 but not wired into the Mock class.
When writing tests that leverage ::Mock to create an instance, Tags are not added nor returned when passing TagSpecification

Perusing the previous issues, it seems common for Mock not to track all of changes in Real, I can take a look at adding TagSpecification into the Mocks if folks are OK with it.

**Comment by geemus** [comment]
@thorrsson Thanks for reaching out. Both real and mock stuff tends to get added when someone has a need (and some time to address it). This often does mean that they can lag one another, depending on specifics of the need and time available. Which is all to say, there isn't a particular reason (that I'm aware of anyway) why we don't yet have this, other than no-one getting around to it yet. It sounds like a great addition if you have the time and inclination. I'm certainly happy to answer questions and provide what support I can along the way too, just let me know.

**Comment by thorrsson** [comment]
💯 @geemus, totally understand the model around the Mock class.

Let me pull something together and get a PR proposed. I'm in the middle of doing an 11 version upgrade of Fog-AWS (3.5.2 -> 3.16.0), if all goes well I should have a PR in the next couple of days.
Thanks!
