### ISSUE TITLE
Is it possible to add `DurationSeconds` in CredentialFetcher ?

### ISSUE THREAD

**Issue by marshluca** [fog/fog-aws#682]
We are trying to access AWS S3 resources through `AWS_WEB_IDENTITY_TOKEN_FILE` in k8s like this:

```ruby
    Fog::AWS::Storage.new(
       region: 'ap-southeast-1',
       use_iam_profile: true,
       role_arn: 'YOUR_AWS_ROLE_ARN'
    )
```

and it works great!
But it looks like it doesn't pass `DurationSeconds` parameter here.
https://github.com/fog/fog-aws/blob/v3.19.0/lib/fog/aws/credential_fetcher.rb#L37C26-L44

```ruby
    params = {
      :Action => "AssumeRoleWithWebIdentity",
      :RoleArn => options[:role_arn] || ENV.fetch("AWS_ROLE_ARN"),
      :RoleSessionName => options[:role_session_name] || ENV["AWS_ROLE_SESSION_NAME"] || "fog-aws-#{SecureRandom.hex}",
      :WebIdentityToken => File.read(options[:aws_web_identity_token_file] || ENV.fetch("AWS_WEB_IDENTITY_TOKEN_FILE")),
      :Version => "2011-06-15",
    }
```

And I noticed we have this parameter in `assume_role_with_web_identity` method here. 
https://github.com/fog/fog-aws/blob/v3.19.0/lib/fog/aws/requests/sts/assume_role_with_web_identity.rb#L13

```ruby
        request_unsigned(
            'Action'            => 'AssumeRoleWithWebIdentity',
            'RoleArn'           => role_arn,
            'RoleSessionName'   => role_session_name,
            'WebIdentityToken'  => web_identity_token,
            'DurationSeconds'   => options[:duration] || 3600,
            :idempotent         => true,
            :parser             => Fog::Parsers::AWS::STS::AssumeRoleWithWebIdentity.new
          )
```

Is it possible to add `DurationSeconds` parameter through `options` in `CredentialFetcher#fetch_credentials`?
I will open a pull request if it is acceptable.
Thanks.

**Comment by geemus** [comment]
I must admit I don't personally have much experience with the assume role and web identity stuff, but that sounds reasonable to me.

I do also wonder why it does that request in such a raw/direct way in the credential fetcher vs calling the assume_role_with_web_identity method. It might also be nice to get rid of that duplication if possible.

I'm open to this change and pull request, so just let me know if you have other questions or need support.

**Comment by marshluca** [comment]
@geemus  thank you for your kind response.

The reason to use the raw way is simply because it's simpler to code like this.

```ruby
ENV["AWS_WEB_IDENTITY_TOKEN_FILE"] = 'YOUR_AWS_WEB_IDENTITY_TOKEN_FILE_PATH'
s3 = Fog::AWS::Storage.new(
      region: 'ap-southeast-1',
      use_iam_profile: true,
      role_arn: 'YOUR_AWS_ROLE_ARN'
)
```

For the current version, It would be appreciated it if it could be aligned 
I am happy to see to get rid of the duplication in the future  :)
