### ISSUE TITLE
When using IRSA on `Fog::Storage`, output `Unrecognized arguments: sts_endpoint` warning 

### ISSUE THREAD

**Issue by nekomaho** [fog/fog-aws#683]
Version: v3.19.0

I pass the following config to connect S3 by [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) using `Fog::Storage`.
```ruby
fog_params = {
  provider: 'AWS',
  region: 'ap-northeast-1',
  use_iam_profile: true,
}
ENV['AWS_ROLE_ARN'] = 'xxxx'
ENV['AWS_STS_REGIONAL_ENDPOINTS'] = 'region'

fog=Fog::Storage.new(fog_params)
```

Then output the following warning. 
```
[fog][WARNING] Unrecognized arguments: sts_endpoint
```
But, in spite of the above warning, the connection to S3 has been successful.
So, this warning seems to be only a display problem.
And this error occurs from the following code.
https://github.com/fog/fog-core/blob/v2.3.0/lib/fog/core/service.rb#L250

I have investigated why this warning occurs and found it seems to be `sts_endpoint` is not include `recognizes` values that are causing that warning.
https://github.com/fog/fog-aws/blob/v3.19.0/lib/fog/aws/storage.rb#L49

In addition, I have tried to add `sts_endpoint` to `recognizes` of `AWS::Fog::Storage` `recognizes`; that warning no longer outputs.

I would like to ask you if `Unrecognized arguments: sts_endpoint` is the correct warning or not.
And if correct, please tell me how to avoid this warning if you know.

**Comment by geemus** [comment]
Thanks for the detailed report. As you noticed, I believe the warning is just a warning, so it should work even if/when it warns.

That being said, I think this is just an oversight. I suspect we missed this case for the recognizes list when we later added the sts options. I think the correct fix is likely to add the `:sts_endpoint` key to the list of recognized warnings. Does that match with your understanding? Would you be up for creating the PR with the fix?

Thanks!

**Comment by nekomaho** [comment]
Thank you for your response!

> I think the correct fix is likely to add the :sts_endpoint key to the list of recognized warnings. Does that match with your understanding?

Yes, it's the same as my understanding.
I'll try to create PR with the fix.

**Comment by geemus** [comment]
Sounds good, thanks!
