### ISSUE TITLE
S3 copy_object won't be retried.

### ISSUE THREAD

**Issue by babatakao** [fog/fog-aws#704]
Since [copy_object](https://github.com/fog/fog-aws/blob/v3.21.1/lib/fog/aws/requests/storage/copy_object.rb#L32-L39) is not mark as idempotent, the copy operation is not retried on error, while other operations such as put_object are retried.

```ruby
s3 = Fog::Storage.new(...)
directory = s3.directories.new(key: 'some-bucket')

directory.files.create(key: 'test', body: 'hello') # this request will be retried on error

file = directory.files.get('test')
file.copy('some-bucket', 'test2') # this request won't be retried on error
```

This behavior is inconvenient and inconsistent.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html says AWS SDK supports retry, so how about changing copy_object as idempotent?

**Comment by geemus** [comment]
Good callout and thanks for the detailed report. This should now be fixed on the main branch, and released in v3.22.0
