### ISSUE TITLE
Support S3 FIPS endpoints, disable S3 Transfer Acceleration in GovCloud or FIPS mode

### ISSUE THREAD

**Issue by matt-domsch-sp** [fog/fog-aws#729]
The Fog::AWS::Utils region_to_host method returns the standard S3 endpoints even when `ENV['AWS_USE_FIPS_ENDPOINT']=='true'.`  When FIPS
 is called for, and we are in a region where FIPS endpoints are
 available,  this method should return the FIPS endpoint.

 Furthermore, when S3 Transfer Acceleration (S3TA) is requested by
 configuration, the above endpoint gets overridden to select the S3TA
 endpoint.  However, S3TA is not avaialble in GovCloud, and has no FIPS
 endpoint equivalents.  In this instance, if the region is a GovCloud
 region, or if FIPS mode is called for, do _not_ override the endpoint
 to use S3TA.

I have a first pass at adding this functionality here for consideration. 
https://github.com/fog/fog-aws/pull/730

**Comment by matt-domsch-sp** [comment]
PR was merged. Closing. Thank you.

**Comment by geemus** [comment]
@matt-domsch-sp thanks for your help and for cleaning this issue up as well.
