### ISSUE TITLE
Add support for EC2 Container Service (ECS)

### ISSUE THREAD

**Issue by nomadium** [fog/fog-aws#93]
Hi,

I'm opening this issue to avoid effort duplication just in case somebody else plans or is already working on this.

I need support for ECS, so I'm implementing this in fog-aws.

Cheers,

**Comment by geemus** [comment]
Cool, thanks for the heads up!

**Comment by hosh** [comment]
:+1: 

Is there code that's usable?

**Comment by nomadium** [comment]
@hosh Yes, you can take a look at my PR https://github.com/fog/fog-aws/pull/120 or directly at my fork https://github.com/nomadium/fog-aws/tree/add-support-for-ecs.

**Comment by geemus** [comment]
Going to just close this in favor of #120. Hoping to get to it soon (still catching up on things after some time away for my wedding).
