### ISSUE TITLE
Enabling termination protection

### ISSUE THREAD

**Issue by nilroy** [fog/fog-aws#95]
I am trying to enable termination protection of instance while launching. I am using {:disable_api_termination => true }  as a parameter to servers.create method. But that does not enable the termination protection. Am I doing something wrong or it is not supported?

**Comment by geemus** [comment]
That looks correct and it appears as though the value would get passed through. So from the code side anyway it looks like it should be supported, I'm not certain where it is getting lost. Are you on the latest version? How are you checking for the final value?

**Comment by nilroy** [comment]
Hi I am on 0.1.2 version. Once I launch the instance I am checking in AWS console to see whether termination protection is enabled or not. Also I checked with fog by creating the aws instance object. The instance object attribute is set to nil. One interesting thing is changing the termination protection from AWS console is not changing the attribute value of the instance object (disable_api_termination is set as nil still)...

**Comment by nilroy** [comment]
Hey...Its working...Somehow my old gemfiles are still there.I cleaned up old versions and everything is working fine. Thanks for your help.

**Comment by geemus** [comment]
No worries, glad to hear you figured it out and thanks for taking the time to update us.
